package com.mycompany.webapp.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Oct 01 21:19:51 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineUserGroupRolePeerImpl
    extends com.mycompany.webapp.om.BaseTurbineUserGroupRolePeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbineUserGroupRolePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1759324791281L;



}
