package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into TurbineUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Oct 01 21:19:51 SGT 2025]
 *
 */
public class TurbineUserRecordMapper extends BaseTurbineUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1759324791418L;



}
