package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into TurbinePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Oct 01 21:19:51 SGT 2025]
 *
 */
public class TurbinePermissionRecordMapper extends BaseTurbinePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1759324791415L;



}
