package com.example.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 07:02:32 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbineRole
    extends com.example.om.BaseTurbineRole
    implements org.apache.fulcrum.security.model.turbine.entity.TurbineRole
{
    /** Serial version */
    private static final long serialVersionUID = 1769036552374L;



}
