package com.example.om;


/**
 * Maps ResultSet rows into TurbineUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 07:02:35 SGT 2026]
 *
 */
public class TurbineUserRecordMapper extends BaseTurbineUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769036555970L;



}
