package com.uob.portal.torque7.om;

/**
 * Maps ResultSet rows into GtpUser objects.
 *
 * The skeleton for this class was autogenerated by Torque.
 */
public class GtpUserRecordMapper extends BaseGtpUserRecordMapper {
    private static final long serialVersionUID = 1L;
}
