package com.uob.om;


/**
 * Maps ResultSet rows into GtpGroupRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:31 SGT 2026]
 *
 */
public class GtpGroupRoleRecordMapper extends BaseGtpGroupRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769088211748L;



}
