package com.uob.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import com.uob.om.TurbineUserGroupRole;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:26 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpGroup
    extends com.uob.om.BaseGtpGroup
    implements org.apache.fulcrum.security.model.turbine.entity.TurbineGroup
{
    /** Serial version */
    private static final long serialVersionUID = 1769088206897L;

    /**
     * Override base class method to use doSelect instead of doSelectJoinGtpRole
     * This prevents joined GtpRole objects from being included in results that
     * maptoModel() processes, which expects only TurbineUserGroupRoleModelPeerMapper objects
     */
    @Override
    protected List<GtpUserGroupRole> getGtpUserGroupRolesJoinGtpRole(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.and(com.uob.om.GtpUserGroupRolePeer.GROUP_ID, getEntityId());
        
        // Use doSelect instead of doSelectJoinGtpRole to avoid joined GtpRole objects
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Set the group reference for each GtpUserGroupRole
        for (GtpUserGroupRole gtpUserGroupRole : gtpUserGroupRoles) {
            gtpUserGroupRole.setGtpGroup(this);
        }
        
        return gtpUserGroupRoles;
    }

    /**
     * Override to use GtpUserGroupRolePeer instead of TurbineUserGroupRolePeer
     * This ensures queries use GTP_USER_GROUP_ROLE table instead of TURBINE_USER_GROUP_ROLE
     * 
     * Note: Using doSelect instead of doSelectJoinGtpRole to avoid joined GtpRole objects
     * being processed by maptoModel(), which expects only TurbineUserGroupRoleModelPeerMapper objects
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineRole(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.where(com.uob.om.GtpUserGroupRolePeer.GROUP_ID, this.getEntityId());
        
        // Use doSelect instead of doSelectJoinGtpRole to avoid joined objects being included
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Convert List<GtpUserGroupRole> to List<TurbineUserGroupRole>
        // Both implement TurbineUserGroupRoleModelPeerMapper, so we use unchecked cast
        // This is safe because both classes implement the same interface
        @SuppressWarnings("unchecked")
        List<TurbineUserGroupRole> result = (List<TurbineUserGroupRole>) (List<?>) gtpUserGroupRoles;
        return result;
    }

}
