package com.uob.om;

import java.sql.Connection;

import org.apache.fulcrum.security.model.turbine.entity.TurbinePermission;
import org.apache.turbine.services.TurbineServices;
import org.apache.turbine.services.security.SecurityService;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:26 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpRolePermission
    extends com.uob.om.BaseGtpRolePermission
    implements org.apache.fulcrum.security.torque.peer.TurbineRolePermissionPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769088206911L;

    /**
     * Get TurbinePermission for this role-permission mapping (without Connection)
     */
    @Override
    public TurbinePermission getTurbinePermission() {
        return getTurbinePermission((Connection) null);
    }

    /**
     * Get TurbinePermission for this role-permission mapping (with Connection)
     */
    public TurbinePermission getTurbinePermission(Connection con) {
        try {
            // Use Torque to get permission by ID
            org.apache.torque.criteria.Criteria criteria = new org.apache.torque.criteria.Criteria();
            criteria.where(com.uob.om.GtpPermissionPeer.PERMISSION_ID, Integer.valueOf(getPermissionId()));
            com.uob.om.GtpPermission permission;
            if (con != null) {
                permission = com.uob.om.GtpPermissionPeer.doSelectSingleRecord(criteria, con);
            } else {
                permission = com.uob.om.GtpPermissionPeer.doSelectSingleRecord(criteria);
            }
            return permission;
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Get TurbineRole for this role-permission mapping (without Connection)
     */
    @Override
    public org.apache.fulcrum.security.entity.Role getTurbineRole() {
        return getTurbineRole((Connection) null);
    }
    
    /**
     * Get TurbineRole for this role-permission mapping (with Connection)
     */
    public org.apache.fulcrum.security.entity.Role getTurbineRole(Connection con) {
        try {
            // Use Torque to get role by ID
            org.apache.torque.criteria.Criteria criteria = new org.apache.torque.criteria.Criteria();
            criteria.where(com.uob.om.GtpRolePeer.ROLE_ID, Integer.valueOf(getRoleId()));
            com.uob.om.GtpRole role;
            if (con != null) {
                role = com.uob.om.GtpRolePeer.doSelectSingleRecord(criteria, con);
            } else {
                role = com.uob.om.GtpRolePeer.doSelectSingleRecord(criteria);
            }
            return role;
        } catch (Exception e) {
            return null;
        }
    }
}
