package com.uob.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import org.apache.fulcrum.security.entity.Group;
import org.apache.turbine.services.TurbineServices;
import org.apache.turbine.services.security.SecurityService;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:34:55 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class GtpUserGroupRolePeerImpl
    extends com.uob.om.BaseGtpUserGroupRolePeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbineUserGroupRolePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1769088895489L;
    
    /** Logger for this class */
    private static final Logger log = LogManager.getLogger(GtpUserGroupRolePeerImpl.class);

    /**
     * Select with join to TurbineGroup
     */
    @Override
    public List<Group> doSelectJoinTurbineGroup(Criteria criteria, Connection con) {
        try {
            SecurityService securityService = (SecurityService) TurbineServices.getInstance().getService(SecurityService.SERVICE_NAME);
            // Use the base implementation and convert to Group list
            List<com.uob.om.GtpUserGroupRole> results = doSelect(criteria, con);
            List<Group> groups = new java.util.ArrayList<>();
            for (com.uob.om.GtpUserGroupRole ugr : results) {
                try {
                    Group group = securityService.getGroupById(Integer.valueOf(ugr.getGroupId()));
                    if (group != null && !groups.contains(group)) {
                        groups.add(group);
                    }
                } catch (Exception e) {
                    // Skip if group not found
                }
            }
            return groups;
        } catch (Exception e) {
            return new java.util.ArrayList<>();
        }
    }

    /**
     * Override doSelectJoinGtpGroup to use doSelect() instead of JOIN query.
     * 
     * The base class method uses a CompositeMapper that creates both GtpUserGroupRole
     * and GtpGroup objects. When this list is passed to maptoModel(), it tries to cast
     * GtpGroup objects to TurbineUserGroupRoleModelPeerMapper, causing ClassCastException.
     * 
     * By using doSelect() instead, we return only GtpUserGroupRole objects, preventing
     * the ClassCastException.
     * 
     * Note: This means GtpGroup objects won't be pre-loaded, but they can be loaded
     * separately if needed.
     */
    @Override
    public List<GtpUserGroupRole> doSelectJoinGtpGroup(Criteria criteria, Connection conn) throws TorqueException {
        log.info("GtpUserGroupRolePeerImpl.doSelectJoinGtpGroup() OVERRIDE CALLED - using doSelect() instead of JOIN");
        System.out.println("GtpUserGroupRolePeerImpl.doSelectJoinGtpGroup() OVERRIDE CALLED - using doSelect() instead of JOIN");
        System.err.println("GtpUserGroupRolePeerImpl.doSelectJoinGtpGroup() OVERRIDE CALLED - using doSelect() instead of JOIN");
        
        // Use doSelect() instead of doSelectJoinGtpGroup() to avoid creating GtpGroup objects
        // This prevents GtpGroup objects from being included in the collection that's
        // passed to maptoModel(), which expects only TurbineUserGroupRoleModelPeerMapper objects
        if (conn != null) {
            return doSelect(criteria, conn);
        } else {
            return doSelect(criteria);
        }
    }
}
