package com.uob.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import com.uob.om.TurbineUserGroupRole;
import org.apache.fulcrum.security.torque.peer.TurbineUserGroupRoleModelPeerMapper;
import org.apache.fulcrum.security.util.DataBackendException;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:26 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpUser
    extends com.uob.om.BaseGtpUser
    implements org.apache.fulcrum.security.model.turbine.entity.TurbineUser
{
    /** Serial version */
    private static final long serialVersionUID = 1769088206915L;
    
    /** Logger for this class */
    private static final Logger log = LogManager.getLogger(GtpUser.class);
    
    // Static initializer to verify class is loaded
    static {
        log.info("GtpUser class loaded - class: " + GtpUser.class.getName());
        System.out.println("GtpUser class loaded - class: " + GtpUser.class.getName());
        System.err.println("GtpUser class loaded - class: " + GtpUser.class.getName());
    }

    /**
     * Override base class method to use doSelect instead of doSelectJoinGtpGroup
     * This prevents joined GtpGroup objects from being included in results that
     * maptoModel() processes, which expects only TurbineUserGroupRoleModelPeerMapper objects
     * 
     * Note: We bypass the base class caching mechanism to ensure we always use doSelect()
     * instead of the cached join results which may contain GtpGroup objects.
     */
    @Override
    protected List<GtpUserGroupRole> getGtpUserGroupRolesJoinGtpGroup(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.and(com.uob.om.GtpUserGroupRolePeer.USER_ID, getEntityId());
        
        // Bypass caching - always use doSelect to avoid joined objects
        // Use doSelect instead of doSelectJoinGtpGroup to avoid joined GtpGroup objects
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Set the user reference for each GtpUserGroupRole
        for (GtpUserGroupRole gtpUserGroupRole : gtpUserGroupRoles) {
            gtpUserGroupRole.setGtpUser(this);
        }
        
        return gtpUserGroupRoles;
    }

    /**
     * Override base class method to use doSelect instead of doSelectJoinGtpRole
     * This prevents joined GtpRole objects from being included in results
     * 
     * Note: We bypass the base class caching mechanism to ensure we always use doSelect()
     * instead of the cached join results which may contain GtpRole objects.
     */
    @Override
    protected List<GtpUserGroupRole> getGtpUserGroupRolesJoinGtpRole(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.and(com.uob.om.GtpUserGroupRolePeer.USER_ID, getEntityId());
        
        // Bypass caching - always use doSelect to avoid joined objects
        // Use doSelect instead of doSelectJoinGtpRole to avoid joined GtpRole objects
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Set the user reference for each GtpUserGroupRole
        for (GtpUserGroupRole gtpUserGroupRole : gtpUserGroupRoles) {
            gtpUserGroupRole.setGtpUser(this);
        }
        
        return gtpUserGroupRoles;
    }

    /**
     * Override to use GtpUserGroupRolePeer instead of TurbineUserGroupRolePeer
     * This ensures queries use GTP_USER_GROUP_ROLE table instead of TURBINE_USER_GROUP_ROLE
     * 
     * Note: Using doSelect instead of doSelectJoinGtpGroup to avoid joined GtpGroup objects
     * being processed by maptoModel(), which expects only TurbineUserGroupRoleModelPeerMapper objects
     */
    @Override
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineGroup(Criteria criteria, Connection connection) throws TorqueException {
        // DEBUG: Log that our override is being called
        log.info("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() OVERRIDE CALLED - userId=" + this.getEntityId());
        System.out.println("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() OVERRIDE CALLED - userId=" + this.getEntityId());
        System.err.println("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() OVERRIDE CALLED - userId=" + this.getEntityId());
        
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.where(com.uob.om.GtpUserGroupRolePeer.USER_ID, this.getEntityId());
        
        // Use doSelect instead of doSelectJoinGtpGroup to avoid joined objects being included
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        log.info("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() returning " + gtpUserGroupRoles.size() + " GtpUserGroupRole objects");
        System.out.println("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() returning " + gtpUserGroupRoles.size() + " GtpUserGroupRole objects");
        System.err.println("GtpUser.getTurbineUserGroupRolesJoinTurbineGroup() returning " + gtpUserGroupRoles.size() + " GtpUserGroupRole objects");
        
        // Convert List<GtpUserGroupRole> to List<TurbineUserGroupRole>
        // Both implement TurbineUserGroupRoleModelPeerMapper, so we use unchecked cast
        // This is safe because both classes implement the same interface
        @SuppressWarnings("unchecked")
        List<TurbineUserGroupRole> result = (List<TurbineUserGroupRole>) (List<?>) gtpUserGroupRoles;
        return result;
    }

    /**
     * Override to use GtpUserGroupRolePeer instead of TurbineUserGroupRolePeer
     * This ensures queries use GTP_USER_GROUP_ROLE table instead of TURBINE_USER_GROUP_ROLE
     * 
     * Note: Using doSelect instead of doSelectJoinGtpRole to avoid joined GtpRole objects
     * being processed by maptoModel(), which expects only TurbineUserGroupRoleModelPeerMapper objects
     * 
     * Note: This method may not exist in the parent class, so we define it without @Override
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineRole(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.where(com.uob.om.GtpUserGroupRolePeer.USER_ID, this.getEntityId());
        
        // Use doSelect instead of doSelectJoinGtpRole to avoid joined objects being included
        // The framework will handle loading related objects separately if needed
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Convert List<GtpUserGroupRole> to List<TurbineUserGroupRole>
        // Both implement TurbineUserGroupRoleModelPeerMapper, so we use unchecked cast
        // This is safe because both classes implement the same interface
        @SuppressWarnings("unchecked")
        List<TurbineUserGroupRole> result = (List<TurbineUserGroupRole>) (List<?>) gtpUserGroupRoles;
        return result;
    }

    /**
     * Override retrieveAttachedObjects to ensure only GtpUserGroupRole objects
     * are processed, preventing GtpGroup objects from being included.
     * 
     * The base class method calls maptoModel() with a collection that includes
     * joined GtpGroup objects, causing ClassCastException. We completely override
     * this method to avoid calling super() which triggers the problematic code path.
     * 
     * We populate the cache directly with only GtpUserGroupRole objects, ensuring
     * that any subsequent calls to get methods return only the correct objects.
     */
    @Override
    public void retrieveAttachedObjects(Connection connection) throws TorqueException, DataBackendException {
        // DEBUG: Log that our override is being called
        // Log with full stack trace to see who's calling us
        log.info("GtpUser.retrieveAttachedObjects() OVERRIDE CALLED - userId=" + this.getEntityId() + ", class=" + this.getClass().getName() + ", superclass=" + this.getClass().getSuperclass().getName());
        log.debug("Call stack:", new Exception("Stack trace"));
        System.out.println("GtpUser.retrieveAttachedObjects() OVERRIDE CALLED - userId=" + this.getEntityId() + ", class=" + this.getClass().getName());
        System.err.println("GtpUser.retrieveAttachedObjects() OVERRIDE CALLED - userId=" + this.getEntityId() + ", class=" + this.getClass().getName());
        
        // Clear cache first to ensure we start fresh
        resetGtpUserGroupRole();
        
        // Pre-populate cache with only GtpUserGroupRole objects using doSelect()
        // This ensures no joined GtpGroup objects are included
        Criteria criteria = new Criteria();
        criteria.where(com.uob.om.GtpUserGroupRolePeer.USER_ID, this.getEntityId());
        
        List<GtpUserGroupRole> gtpUserGroupRoles;
        if (connection != null) {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria, connection);
        } else {
            gtpUserGroupRoles = com.uob.om.GtpUserGroupRolePeer.doSelect(criteria);
        }
        
        // Set the user reference for each GtpUserGroupRole
        for (GtpUserGroupRole gtpUserGroupRole : gtpUserGroupRoles) {
            gtpUserGroupRole.setGtpUser(this);
        }
        
        // Populate collGtpUserGroupRoles cache directly
        // We do NOT call super() to avoid the base class calling maptoModel()
        // with a collection that contains GtpGroup objects
        if (connection != null) {
            List<GtpUserGroupRole> cached = getGtpUserGroupRoles(connection);
            cached.clear();
            cached.addAll(gtpUserGroupRoles);
        } else {
            List<GtpUserGroupRole> cached = getGtpUserGroupRoles();
            cached.clear();
            cached.addAll(gtpUserGroupRoles);
        }
        
        // DO NOT call super.retrieveAttachedObjects(connection) because it calls
        // maptoModel() with a collection that contains GtpGroup objects, causing
        // ClassCastException. Our cache is now populated with only GtpUserGroupRole
        // objects, which is what we need.
    }

}
