package com.uob.om;


/**
 * Maps ResultSet rows into GtpUserGroupRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:34:57 SGT 2026]
 *
 */
public class GtpUserGroupRoleRecordMapper extends BaseGtpUserGroupRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769088897470L;



}
