package com.example.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 18:07:13 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Author
    extends com.example.om.BaseAuthor
{
    /** Serial version */
    private static final long serialVersionUID = 1758967633863L;



}
