package com.example.om;


/**
 * Maps ResultSet rows into GtpPermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 18:07:16 SGT 2025]
 *
 */
public class GtpPermissionRecordMapper extends BaseGtpPermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758967636505L;



}
