package com.example.om;

import java.sql.Connection;

import org.apache.fulcrum.security.entity.Permission;
import org.apache.fulcrum.security.entity.Role;
import org.apache.fulcrum.security.model.turbine.entity.TurbinePermission;
import org.apache.torque.TorqueException;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 18:07:14 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpRolePermission
    extends com.example.om.BaseGtpRolePermission
    implements org.apache.fulcrum.security.torque.peer.TurbineRolePermissionPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758967634004L;

	@Override
	public Role getTurbineRole() throws TorqueException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Role getTurbineRole(Connection connection) throws TorqueException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Permission getTurbinePermission() throws TorqueException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public TurbinePermission getTurbinePermission(Connection connection) throws TorqueException {
		// TODO Auto-generated method stub
		return null;
	}



}
