package com.example.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 18:07:15 SGT 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class GtpUserPeer
    extends com.example.om.BaseGtpUserPeer
{

}
