package com.example.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 18:07:15 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class GtpUserGroupRolePeerImpl
    extends com.example.om.BaseGtpUserGroupRolePeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbineUserGroupRolePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1758967635649L;

	@Override
	public List doSelectJoinTurbineGroup(Criteria criteria, Connection con) throws TorqueException {
		// TODO Auto-generated method stub
		return null;
	}



}
