package com.mycompany.webapp.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 16:01:52 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineRolePermissionPeerImpl
    extends com.mycompany.webapp.om.BaseTurbineRolePermissionPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1756108912132L;



}
