package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into TurbineUserGroupRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 16:01:52 SGT 2025]
 *
 */
public class TurbineUserGroupRoleRecordMapper extends BaseTurbineUserGroupRoleRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1756108912537L;



}
