package com.mycompany.webapp.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 16:01:51 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbinePermission
    extends com.mycompany.webapp.om.BaseTurbinePermission
    implements org.apache.fulcrum.security.model.turbine.entity.TurbinePermission
{
    /** Serial version */
    private static final long serialVersionUID = 1756108911043L;



}
