package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into TurbineUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 16:01:52 SGT 2025]
 *
 */
public class TurbineUserRecordMapper extends BaseTurbineUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1756108912534L;



}
