package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into GtpGroupRolePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Sep 26 15:12:59 SGT 2025]
 *
 */
public class GtpGroupRolePermissionRecordMapper extends BaseGtpGroupRolePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758870779189L;



}
