package com.mycompany.webapp.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Sep 26 15:12:57 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpUserRole
    extends com.mycompany.webapp.om.BaseGtpUserRole
{
    /** Serial version */
    private static final long serialVersionUID = 1758870777818L;



}
