package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into GtpUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Sep 26 15:12:59 SGT 2025]
 *
 */
public class GtpUserRecordMapper extends BaseGtpUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758870779173L;



}
