package com.example.om;


/**
 * Maps ResultSet rows into TurbineGroup objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 19:39:22 SGT 2025]
 *
 */
public class TurbineGroupRecordMapper extends BaseTurbineGroupRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758973162968L;



}
