package com.example.om;


/**
 * Maps ResultSet rows into TurbineUser objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Sep 27 19:39:22 SGT 2025]
 *
 */
public class TurbineUserRecordMapper extends BaseTurbineUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1758973162973L;



}
