package com.uob.om;

import java.sql.Connection;

import org.apache.fulcrum.security.entity.Role;
import org.apache.fulcrum.security.util.UnknownEntityException;
import org.apache.turbine.services.TurbineServices;
import org.apache.turbine.services.security.SecurityService;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:26 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpGroupRole
    extends com.uob.om.BaseGtpGroupRole
    implements org.apache.fulcrum.security.torque.peer.TurbineUserGroupRoleModelPeerMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769088206926L;

    /**
     * Get TurbineRole for this group-role mapping (without Connection)
     */
    @Override
    public Role getTurbineRole() {
        return getTurbineRole((Connection) null);
    }

    /**
     * Get TurbineRole for this group-role mapping (with Connection)
     */
    public Role getTurbineRole(Connection con) {
        try {
            // Use Torque to get role by ID
            org.apache.torque.criteria.Criteria criteria = new org.apache.torque.criteria.Criteria();
            criteria.where(com.uob.om.GtpRolePeer.ROLE_ID, Integer.valueOf(getRoleId()));
            com.uob.om.GtpRole role;
            if (con != null) {
                role = com.uob.om.GtpRolePeer.doSelectSingleRecord(criteria, con);
            } else {
                role = com.uob.om.GtpRolePeer.doSelectSingleRecord(criteria);
            }
            return role;
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Get TurbineGroup for this group-role mapping (without Connection)
     */
    @Override
    public org.apache.fulcrum.security.entity.Group getTurbineGroup() {
        return getTurbineGroup((Connection) null);
    }
    
    /**
     * Get TurbineGroup for this group-role mapping (with Connection)
     */
    public org.apache.fulcrum.security.entity.Group getTurbineGroup(Connection con) {
        try {
            // Use Torque to get group by ID
            org.apache.torque.criteria.Criteria criteria = new org.apache.torque.criteria.Criteria();
            criteria.where(com.uob.om.GtpGroupPeer.GROUP_ID, Integer.valueOf(getGroupId()));
            com.uob.om.GtpGroup group;
            if (con != null) {
                group = com.uob.om.GtpGroupPeer.doSelectSingleRecord(criteria, con);
            } else {
                group = com.uob.om.GtpGroupPeer.doSelectSingleRecord(criteria);
            }
            return group;
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Get TurbineUser for this group-role mapping (without Connection)
     * Note: GroupRole doesn't have a direct user, but interface requires this method
     */
    @Override
    public org.apache.turbine.om.security.User getTurbineUser() {
        return getTurbineUser((Connection) null);
    }
    
    /**
     * Get TurbineUser for this group-role mapping (with Connection)
     * Note: GroupRole doesn't have a direct user, but interface requires this method
     */
    public org.apache.turbine.om.security.User getTurbineUser(Connection con) {
        // GroupRole doesn't have a user - return null
        return null;
    }
}
