package com.uob.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import com.uob.om.TurbineRolePermission;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:26 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class GtpPermission
    extends com.uob.om.BaseGtpPermission
    implements org.apache.fulcrum.security.model.turbine.entity.TurbinePermission
{
    /** Serial version */
    private static final long serialVersionUID = 1769088206878L;

    /**
     * Override to use GtpRolePermissionPeer instead of TurbineRolePermissionPeer
     * This ensures queries use GTP_ROLE_PERMISSION table instead of TURBINE_ROLE_PERMISSION
     */
    protected List<TurbineRolePermission> getTurbineRolePermissionsJoinTurbineRole(Criteria criteria, Connection connection) throws TorqueException {
        if (criteria == null) {
            criteria = new Criteria();
        }
        criteria.where(com.uob.om.GtpRolePermissionPeer.PERMISSION_ID, this.getEntityId());
        
        // Use GtpRolePermissionPeer which queries GTP_ROLE_PERMISSION table
        // GtpRolePermission implements TurbineRolePermissionPeerMapper, so it's compatible
        List<GtpRolePermission> gtpRolePermissions;
        if (connection != null) {
            gtpRolePermissions = com.uob.om.GtpRolePermissionPeer.doSelectJoinGtpRole(criteria, connection);
        } else {
            gtpRolePermissions = com.uob.om.GtpRolePermissionPeer.doSelectJoinGtpRole(criteria);
        }
        
        // Convert List<GtpRolePermission> to List<TurbineRolePermission>
        // Since GtpRolePermission implements TurbineRolePermissionPeerMapper, we can cast
        @SuppressWarnings("unchecked")
        List<TurbineRolePermission> result = (List<TurbineRolePermission>) (List<?>) gtpRolePermissions;
        return result;
    }

}
