package com.uob.om;

import java.sql.Connection;
import java.util.List;

import org.apache.torque.criteria.Criteria;
import org.apache.fulcrum.security.entity.Group;
import org.apache.turbine.services.TurbineServices;
import org.apache.turbine.services.security.SecurityService;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:34:55 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class GtpUserGroupRolePeerImpl
    extends com.uob.om.BaseGtpUserGroupRolePeerImpl
    implements org.apache.fulcrum.security.torque.peer.TorqueTurbineUserGroupRolePeer
{
    /** Serial version */
    private static final long serialVersionUID = 1769088895489L;

    /**
     * Select with join to TurbineGroup
     */
    @Override
    public List<Group> doSelectJoinTurbineGroup(Criteria criteria, Connection con) {
        try {
            SecurityService securityService = (SecurityService) TurbineServices.getInstance().getService(SecurityService.SERVICE_NAME);
            // Use the base implementation and convert to Group list
            List<com.uob.om.GtpUserGroupRole> results = doSelect(criteria, con);
            List<Group> groups = new java.util.ArrayList<>();
            for (com.uob.om.GtpUserGroupRole ugr : results) {
                try {
                    Group group = securityService.getGroupById(Integer.valueOf(ugr.getGroupId()));
                    if (group != null && !groups.contains(group)) {
                        groups.add(group);
                    }
                } catch (Exception e) {
                    // Skip if group not found
                }
            }
            return groups;
        } catch (Exception e) {
            return new java.util.ArrayList<>();
        }
    }
}
