package com.uob.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:30 SGT 2026]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class TurbineRolePermissionPeerImpl
    extends com.uob.om.BaseTurbineRolePermissionPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1769088210416L;



}
