package com.uob.om;


/**
 * Maps ResultSet rows into TurbineGroup objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jan 22 21:23:31 SGT 2026]
 *
 */
public class TurbineGroupRecordMapper extends BaseTurbineGroupRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1769088211762L;



}
