package com.uob.om;

import java.io.Serializable;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.om.ColumnAccessByName;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.util.TorqueConnection;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 *
 * [Sat Jan 24 10:52:44 SGT 2026]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to TurbineUser
 */
@SuppressWarnings("unused")
public abstract class BaseTurbineUser extends org.apache.fulcrum.security.torque.turbine.DefaultAbstractTurbineUser
    implements Persistent, Serializable, ColumnAccessByName
{
    /** Serial version */
    private static final long serialVersionUID = 1769223164162L;



    /** Defines the entityId field. */
    private Integer entityId = null;

    /** Defines the entityName field. */
    private String entityName = null;

    /** Defines the password field. */
    private String password = null;

    /** Defines the firstName field. */
    private String firstName = null;

    /** Defines the lastName field. */
    private String lastName = null;

    /** Defines the email field. */
    private String email = null;

    /** Defines the confirmed field. */
    private String confirmed = null;

    /** Defines the modifiedDate field. */
    private java.util.Date modifiedDate = null;

    /** Defines the createDate field. */
    private java.util.Date createDate = null;

    /** Defines the lastLogin field. */
    private java.util.Date lastLogin = null;

    /** Defines the objectdata field. */
    private byte[] objectdata = null;

    /** Whether this object was modified after loading or after last save. */
    private boolean modified = true;

    /** 
     * Whether this object was loaded from the database or already saved 
     * (false) or whether it is not yet in the database(true).
     */
    private boolean isNew = true;

    /** Flag which indicates whether this object is currently saving. */
    private boolean saving = false;

    /** 
     * Flag which indicates whether this object is currently loaded
     * from the database. 
     */
    private boolean loading = false;

    /** 
     * Flag which indicates whether this object was deleted from the database.
     * Note that this flags does not always display the current database state,
     * there is no magical connection between this flag and the database.
     */
    private boolean deleted = false;



    /** Defines the collTurbineUserGroupRoles field. */
    protected List<TurbineUserGroupRole> collTurbineUserGroupRoles = null;



    /**
     * Get the value of entityId.
     *
     * @return the value of entityId as Integer
     */
    public Integer getEntityId() 
    {
        
        return entityId;
    }

    /**
     * Set the value of entityId.
     *
     * @param v new value of entityId
     */
    public void setEntityId(Integer v)
    {
        if (!Objects.equals(this.entityId, v))
        {
            setModified(true);
        }

        this.entityId = v;

        // update associated objects in collTurbineUserGroupRoles 
        if (collTurbineUserGroupRoles != null)
        {
            for (TurbineUserGroupRole element : collTurbineUserGroupRoles)
            {
                element.setUserId(v);
            }
        }

    }
    
    /**
     * Get the value of entityName.
     *
     * @return the value of entityName as String
     */
    public String getEntityName() 
    {
        
        return entityName;
    }

    /**
     * Set the value of entityName.
     *
     * @param v new value of entityName
     */
    public void setEntityName(String v)
    {
        if (!Objects.equals(this.entityName, v))
        {
            setModified(true);
        }

        this.entityName = v;


    }
    
    /**
     * Get the value of password.
     *
     * @return the value of password as String
     */
    public String getPassword() 
    {
        
        return password;
    }

    /**
     * Set the value of password.
     *
     * @param v new value of password
     */
    public void setPassword(String v)
    {
        if (!Objects.equals(this.password, v))
        {
            setModified(true);
        }

        this.password = v;


    }
    
    /**
     * Get the value of firstName.
     *
     * @return the value of firstName as String
     */
    public String getFirstName() 
    {
        
        return firstName;
    }

    /**
     * Set the value of firstName.
     *
     * @param v new value of firstName
     */
    public void setFirstName(String v)
    {
        if (!Objects.equals(this.firstName, v))
        {
            setModified(true);
        }

        this.firstName = v;


    }
    
    /**
     * Get the value of lastName.
     *
     * @return the value of lastName as String
     */
    public String getLastName() 
    {
        
        return lastName;
    }

    /**
     * Set the value of lastName.
     *
     * @param v new value of lastName
     */
    public void setLastName(String v)
    {
        if (!Objects.equals(this.lastName, v))
        {
            setModified(true);
        }

        this.lastName = v;


    }
    
    /**
     * Get the value of email.
     *
     * @return the value of email as String
     */
    public String getEmail() 
    {
        
        return email;
    }

    /**
     * Set the value of email.
     *
     * @param v new value of email
     */
    public void setEmail(String v)
    {
        if (!Objects.equals(this.email, v))
        {
            setModified(true);
        }

        this.email = v;


    }
    
    /**
     * Get the value of confirmed.
     *
     * @return the value of confirmed as String
     */
    public String getConfirmed() 
    {
        
        return confirmed;
    }

    /**
     * Set the value of confirmed.
     *
     * @param v new value of confirmed
     */
    public void setConfirmed(String v)
    {
        if (!Objects.equals(this.confirmed, v))
        {
            setModified(true);
        }

        this.confirmed = v;


    }
    
    /**
     * Get the value of modifiedDate.
     *
     * @return the value of modifiedDate as java.util.Date
     */
    public java.util.Date getModifiedDate() 
    {
        
        return modifiedDate;
    }

    /**
     * Set the value of modifiedDate.
     *
     * @param v new value of modifiedDate
     */
    public void setModifiedDate(java.util.Date v)
    {
        if (!Objects.equals(this.modifiedDate, v))
        {
            setModified(true);
        }

        this.modifiedDate = v;


    }
    
    /**
     * Get the value of createDate.
     *
     * @return the value of createDate as java.util.Date
     */
    public java.util.Date getCreateDate() 
    {
        
        return createDate;
    }

    /**
     * Set the value of createDate.
     *
     * @param v new value of createDate
     */
    public void setCreateDate(java.util.Date v)
    {
        if (!Objects.equals(this.createDate, v))
        {
            setModified(true);
        }

        this.createDate = v;


    }
    
    /**
     * Get the value of lastLogin.
     *
     * @return the value of lastLogin as java.util.Date
     */
    public java.util.Date getLastLogin() 
    {
        
        return lastLogin;
    }

    /**
     * Set the value of lastLogin.
     *
     * @param v new value of lastLogin
     */
    public void setLastLogin(java.util.Date v)
    {
        if (!Objects.equals(this.lastLogin, v))
        {
            setModified(true);
        }

        this.lastLogin = v;


    }
    
    /**
     * Get the value of objectdata.
     *
     * @return the value of objectdata as byte[]
     */
    public byte[] getObjectdata() 
    {
        
        return objectdata;
    }

    /**
     * Set the value of objectdata.
     *
     * @param v new value of objectdata
     */
    public void setObjectdata(byte[] v)
    {
        if (!Objects.equals(this.objectdata, v))
        {
            setModified(true);
        }

        this.objectdata = v;


    }
    

    /**
     * Returns whether the object has ever been saved.  This will
     * be false, if the object was retrieved from storage or was created
     * and then saved.
     *
     * @return true, if the object has never been persisted.
     */
    public boolean isNew()
    {
        return isNew;
    }

    /**
     * Sets whether the object has ever been saved.
     *
     * @param isNew true if the object has never been saved, false otherwise.
     */
    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }

    /**
     * Returns whether the object has been modified.
     *
     * @return True if the object has been modified.
     */
    public boolean isModified()
    {
        return modified;
    }

    /**
     * Sets whether the object has been modified.
     *
     * @param modified true if the object has been modified, false otherwise.
     */
    public void setModified(boolean modified)
    {
        this.modified = modified;
    }

    /**
     * Sets the modified state for the object to be false.
     */
    public void resetModified()
    {
        modified = false;
    }


    /**
     * Returns whether this object is currently saving.
     *
     * @return true if this object is currently saving, false otherwise.
     */
    public boolean isSaving()
    {
        return saving;
    }

    /**
     * Sets whether this object is currently saving.
     *
     * @param saving true if this object is currently saving, false otherwise.
     */
    public void setSaving(boolean saving)
    {
        this.saving = saving;
    }


    /**
     * Returns whether this object is currently being loaded from the database.
     *
     * @return true if this object is currently loading, false otherwise.
     */
    public boolean isLoading()
    {
        return loading;
    }

    /**
     * Sets whether this object is currently being loaded from the database.
     *
     * @param loading true if this object is currently loading, false otherwise.
     */
    public void setLoading(boolean loading)
    {
        this.loading = loading;
    }


    /**
     * Returns whether this object was deleted from the database.
     * Note that this getter does not automatically reflect database state,
     * it will be set to true by Torque if doDelete() was called with this 
     * object. Bulk deletes and deletes via primary key do not change
     * this flag. Also, if doDelete() was called on an object which does
     * not exist in the database, the deleted flag is set to true even if
     * it was not deleted.
     *
     * @return true if this object was deleted, false otherwise.
     */
    public boolean isDeleted()
    {
        return deleted;
    }

    /**
     * Sets whether this object was deleted from the database.
     *
     * @param deleted true if this object was deleted, false otherwise.
     */
    public void setDeleted(boolean deleted)
    {
        this.deleted = deleted;
    }




    /**
     * Initializes the cache collTurbineUserGroupRoles for referenced objects.
     * This, means, if collTurbineUserGroupRoles is null when this operation is called, it is
     * initialized with an empty collection, otherwise it remains unchanged. 
     *
     * @return the (possibly new) content of the field collTurbineUserGroupRoles, not null.
     */
    public List<TurbineUserGroupRole> initTurbineUserGroupRoles()
    {
        if (collTurbineUserGroupRoles == null)
        {
            collTurbineUserGroupRoles = new ArrayList<TurbineUserGroupRole>();
        }
        return collTurbineUserGroupRoles;
    }

    /**
     * Checks whether the cache collTurbineUserGroupRoles for referenced objects has either been
     * loaded from the database or has been manually initialized.
     *
     * @return boolean true if initialized
     */
    public boolean isTurbineUserGroupRolesInitialized()
    {
        return (collTurbineUserGroupRoles != null);
    }


    /**
     * Method called to associate a TurbineUserGroupRole object to this object
     * through the collTurbineUserGroupRoles foreign key attribute.
     * If the associated objects were not retrieved before
     * and this object is not new, the associated objects are retrieved
     * from the database before adding the <code>toAdd</code> object.
     *
     * @param toAdd the object to add to the associated objects, not null.
     *
     * @throws TorqueException if retrieval of the associated objects fails.
     * @throws NullPointerException if toAdd is null.
     */
    public void addTurbineUserGroupRole(TurbineUserGroupRole toAdd)
        throws TorqueException
    {
        toAdd.setTurbineUser((TurbineUser) this);
        getTurbineUserGroupRoles().add(toAdd);
    }

    /**
     * Method called to associate a TurbineUserGroupRole object to this object
     * through the collTurbineUserGroupRoles foreign key attribute using connection.
     *
     * @param l TurbineUserGroupRole
     * @throws TorqueException if retrieval of the associated objects fails.
     */
    public void addTurbineUserGroupRole(TurbineUserGroupRole l, Connection con) throws TorqueException
    {
        getTurbineUserGroupRoles(con).add(l);
        l.setTurbineUser((TurbineUser) this);
    }
    
    /**
     * Method called to reset the cache of TurbineUserGroupRole objects
     * which are related through the collTurbineUserGroupRoles foreign key attribute.
     */
    public void resetTurbineUserGroupRole()
    {
        collTurbineUserGroupRoles = null;
    }


    /**
     * The criteria used to select the current contents of collTurbineUserGroupRoles
     */
    private transient Criteria lastTurbineUserGroupRoleCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTurbineUserGroupRoles(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<TurbineUserGroupRole> getTurbineUserGroupRoles()
        throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            collTurbineUserGroupRoles = getTurbineUserGroupRoles(new Criteria());
            for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
            {
                turbineUserGroupRole.setTurbineUser((TurbineUser) this);
            }
        }
        return collTurbineUserGroupRoles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser has previously
     * been saved, it will retrieve related collTurbineUserGroupRoles from storage.
     * If this BaseTurbineUser is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException If a problem occurs with the get[criteria] method.     
     */
    public List<TurbineUserGroupRole> getTurbineUserGroupRoles(Criteria criteria) throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            if (isNew())
            {
               initTurbineUserGroupRoles();
            }
            else
            {
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelect(criteria);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                if (lastTurbineUserGroupRoleCriteria == null
                        || !lastTurbineUserGroupRoleCriteria.equals(criteria))
                {
                    collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelect(criteria);
                    for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                    {
                        turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                    }
                }
            }
        }
        lastTurbineUserGroupRoleCriteria = criteria;
        return collTurbineUserGroupRoles;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTurbineUserGroupRoles(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<TurbineUserGroupRole> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<TurbineUserGroupRole> getTurbineUserGroupRoles(Connection con) throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            collTurbineUserGroupRoles = getTurbineUserGroupRoles(new Criteria(), con);
            for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
            {
                turbineUserGroupRole.setTurbineUser((TurbineUser) this);
            }
        }
        return collTurbineUserGroupRoles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser has previously
     * been saved, it will retrieve the related TurbineUserGroupRole Objects
     * from storage.
     * If this BaseTurbineUser is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<TurbineUserGroupRole> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<TurbineUserGroupRole> getTurbineUserGroupRoles(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            if (isNew())
            {
               initTurbineUserGroupRoles();
            }
            else
            {
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelect(criteria, con);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        else
        {
             // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                if (lastTurbineUserGroupRoleCriteria == null
                        || !lastTurbineUserGroupRoleCriteria.equals(criteria))
                {
                    collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelect(criteria, con);
                    for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                    {
                        turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                    }
                }
            }
        }
        lastTurbineUserGroupRoleCriteria = criteria;

        return collTurbineUserGroupRoles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     *
     * @return List<TurbineUserGroupRole> the collection
     * @param criteria the criteria to use when filling the collection.
     * @throws TorqueException if associated objects are not found
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineGroup(Criteria criteria) throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(criteria.getDbName()))
        {
            List<TurbineUserGroupRole> result = getTurbineUserGroupRolesJoinTurbineGroup(criteria, connection);

            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser is new, it will return
     * an empty collection; or if this BaseTurbineUser has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineGroup(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            if (isNew())
            {
                initTurbineUserGroupRoles();
            }
            else
            {
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelectJoinTurbineGroup(criteria, connection);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
            if (lastTurbineUserGroupRoleCriteria == null
                        || !lastTurbineUserGroupRoleCriteria.equals(criteria))
            {
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelectJoinTurbineGroup(criteria, connection);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        lastTurbineUserGroupRoleCriteria = criteria;

        return collTurbineUserGroupRoles;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     *
     * @return List<TurbineUserGroupRole> the collection
     * @param criteria the criteria to use when filling the collection.
     * @throws TorqueException if associated objects are not found
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineRole(Criteria criteria) throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(criteria.getDbName()))
        {
            List<TurbineUserGroupRole> result = getTurbineUserGroupRolesJoinTurbineRole(criteria, connection);

            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbineUser is new, it will return
     * an empty collection; or if this BaseTurbineUser has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<TurbineUserGroupRole> getTurbineUserGroupRolesJoinTurbineRole(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collTurbineUserGroupRoles == null)
        {
            if (isNew())
            {
                initTurbineUserGroupRoles();
            }
            else
            {
                criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelectJoinTurbineRole(criteria, connection);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(com.uob.om.TurbineUserGroupRolePeer.USER_ID, getEntityId());
            if (lastTurbineUserGroupRoleCriteria == null
                        || !lastTurbineUserGroupRoleCriteria.equals(criteria))
            {
                collTurbineUserGroupRoles = com.uob.om.TurbineUserGroupRolePeer.doSelectJoinTurbineRole(criteria, connection);
                for (TurbineUserGroupRole turbineUserGroupRole : collTurbineUserGroupRoles)
                {
                    turbineUserGroupRole.setTurbineUser((TurbineUser) this);
                }
            }
        }
        lastTurbineUserGroupRoleCriteria = criteria;

        return collTurbineUserGroupRoles;
    }




    private static final List<String> FIELD_NAMES;

    static
    {
        List<String> fieldNames
                = new ArrayList<String>();
        fieldNames.add("EntityId");
        fieldNames.add("EntityName");
        fieldNames.add("Password");
        fieldNames.add("FirstName");
        fieldNames.add("LastName");
        fieldNames.add("Email");
        fieldNames.add("Confirmed");
        fieldNames.add("ModifiedDate");
        fieldNames.add("CreateDate");
        fieldNames.add("LastLogin");
        fieldNames.add("Objectdata");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static List<String> getFieldNames()
    {
        return FIELD_NAMES;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("EntityId"))
        {
            return getEntityId();
        }
        if (name.equals("EntityName"))
        {
            return getEntityName();
        }
        if (name.equals("Password"))
        {
            return getPassword();
        }
        if (name.equals("FirstName"))
        {
            return getFirstName();
        }
        if (name.equals("LastName"))
        {
            return getLastName();
        }
        if (name.equals("Email"))
        {
            return getEmail();
        }
        if (name.equals("Confirmed"))
        {
            return getConfirmed();
        }
        if (name.equals("ModifiedDate"))
        {
            return getModifiedDate();
        }
        if (name.equals("CreateDate"))
        {
            return getCreateDate();
        }
        if (name.equals("LastLogin"))
        {
            return getLastLogin();
        }
        if (name.equals("Objectdata"))
        {
            return getObjectdata();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("EntityId"))
        {
            // Object fields can be null
            if (value != null && ! Integer.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEntityId((Integer) value);
            return true;
        }
        if (name.equals("EntityName"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEntityName((String) value);
            return true;
        }
        if (name.equals("Password"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setPassword((String) value);
            return true;
        }
        if (name.equals("FirstName"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setFirstName((String) value);
            return true;
        }
        if (name.equals("LastName"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setLastName((String) value);
            return true;
        }
        if (name.equals("Email"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEmail((String) value);
            return true;
        }
        if (name.equals("Confirmed"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setConfirmed((String) value);
            return true;
        }
        if (name.equals("ModifiedDate"))
        {
            // Object fields can be null
            if (value != null && ! java.util.Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setModifiedDate((java.util.Date) value);
            return true;
        }
        if (name.equals("CreateDate"))
        {
            // Object fields can be null
            if (value != null && ! java.util.Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCreateDate((java.util.Date) value);
            return true;
        }
        if (name.equals("LastLogin"))
        {
            // Object fields can be null
            if (value != null && ! java.util.Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setLastLogin((java.util.Date) value);
            return true;
        }
        if (name.equals("Objectdata"))
        {
            // Object fields can be null
            if (value != null && ! byte[].class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setObjectdata((byte[]) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (com.uob.om.TurbineUserPeer.USER_ID.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.USER_ID.getColumnName().equals(name))
        {
            return getEntityId();
        }
        if (com.uob.om.TurbineUserPeer.LOGIN_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LOGIN_NAME.getColumnName().equals(name))
        {
            return getEntityName();
        }
        if (com.uob.om.TurbineUserPeer.PASSWORD_VALUE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.PASSWORD_VALUE.getColumnName().equals(name))
        {
            return getPassword();
        }
        if (com.uob.om.TurbineUserPeer.FIRST_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.FIRST_NAME.getColumnName().equals(name))
        {
            return getFirstName();
        }
        if (com.uob.om.TurbineUserPeer.LAST_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LAST_NAME.getColumnName().equals(name))
        {
            return getLastName();
        }
        if (com.uob.om.TurbineUserPeer.EMAIL.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.EMAIL.getColumnName().equals(name))
        {
            return getEmail();
        }
        if (com.uob.om.TurbineUserPeer.CONFIRM_VALUE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.CONFIRM_VALUE.getColumnName().equals(name))
        {
            return getConfirmed();
        }
        if (com.uob.om.TurbineUserPeer.MODIFIED_DATE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.MODIFIED_DATE.getColumnName().equals(name))
        {
            return getModifiedDate();
        }
        if (com.uob.om.TurbineUserPeer.CREATED.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.CREATED.getColumnName().equals(name))
        {
            return getCreateDate();
        }
        if (com.uob.om.TurbineUserPeer.LAST_LOGIN.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LAST_LOGIN.getColumnName().equals(name))
        {
            return getLastLogin();
        }
        if (com.uob.om.TurbineUserPeer.OBJECTDATA.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.OBJECTDATA.getColumnName().equals(name))
        {
            return getObjectdata();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (com.uob.om.TurbineUserPeer.USER_ID.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.USER_ID.getColumnName().equals(name))
        {
            return setByName("EntityId", value);
        }
        if (com.uob.om.TurbineUserPeer.LOGIN_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LOGIN_NAME.getColumnName().equals(name))
        {
            return setByName("EntityName", value);
        }
        if (com.uob.om.TurbineUserPeer.PASSWORD_VALUE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.PASSWORD_VALUE.getColumnName().equals(name))
        {
            return setByName("Password", value);
        }
        if (com.uob.om.TurbineUserPeer.FIRST_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.FIRST_NAME.getColumnName().equals(name))
        {
            return setByName("FirstName", value);
        }
        if (com.uob.om.TurbineUserPeer.LAST_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LAST_NAME.getColumnName().equals(name))
        {
            return setByName("LastName", value);
        }
        if (com.uob.om.TurbineUserPeer.EMAIL.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.EMAIL.getColumnName().equals(name))
        {
            return setByName("Email", value);
        }
        if (com.uob.om.TurbineUserPeer.CONFIRM_VALUE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.CONFIRM_VALUE.getColumnName().equals(name))
        {
            return setByName("Confirmed", value);
        }
        if (com.uob.om.TurbineUserPeer.MODIFIED_DATE.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.MODIFIED_DATE.getColumnName().equals(name))
        {
            return setByName("ModifiedDate", value);
        }
        if (com.uob.om.TurbineUserPeer.CREATED.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.CREATED.getColumnName().equals(name))
        {
            return setByName("CreateDate", value);
        }
        if (com.uob.om.TurbineUserPeer.LAST_LOGIN.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.LAST_LOGIN.getColumnName().equals(name))
        {
            return setByName("LastLogin", value);
        }
        if (com.uob.om.TurbineUserPeer.OBJECTDATA.getSqlExpression().equals(name)
            || com.uob.om.TurbineUserPeer.OBJECTDATA.getColumnName().equals(name))
        {
            return setByName("Objectdata", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getEntityId();
        }
        if (pos == 1)
        {
            return getEntityName();
        }
        if (pos == 2)
        {
            return getPassword();
        }
        if (pos == 3)
        {
            return getFirstName();
        }
        if (pos == 4)
        {
            return getLastName();
        }
        if (pos == 5)
        {
            return getEmail();
        }
        if (pos == 6)
        {
            return getConfirmed();
        }
        if (pos == 7)
        {
            return getModifiedDate();
        }
        if (pos == 8)
        {
            return getCreateDate();
        }
        if (pos == 9)
        {
            return getLastLogin();
        }
        if (pos == 10)
        {
            return getObjectdata();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("EntityId", value);
        }
        if (position == 1)
        {
            return setByName("EntityName", value);
        }
        if (position == 2)
        {
            return setByName("Password", value);
        }
        if (position == 3)
        {
            return setByName("FirstName", value);
        }
        if (position == 4)
        {
            return setByName("LastName", value);
        }
        if (position == 5)
        {
            return setByName("Email", value);
        }
        if (position == 6)
        {
            return setByName("Confirmed", value);
        }
        if (position == 7)
        {
            return setByName("ModifiedDate", value);
        }
        if (position == 8)
        {
            return setByName("CreateDate", value);
        }
        if (position == 9)
        {
            return setByName("LastLogin", value);
        }
        if (position == 10)
        {
            return setByName("Objectdata", value);
        }
        return false;
    }



    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save() throws TorqueException
    {
        save(TurbineUserPeer.DATABASE_NAME);
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param dbName the name of the database to which the object
     *        should be saved.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(String dbName) 
            throws TorqueException
    {
        try (TorqueConnection con = Transaction.begin(dbName))
        {
            save(con);
            Transaction.commit(con);
        }
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally.
     *
     * @param con the connection to use for saving the object, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(Connection con) 
            throws TorqueException
    {
        if (isSaving())
        {
            return;
        }
        try
        {
            setSaving(true);
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    TurbineUserPeer.doInsert((TurbineUser) this, con);
                    setNew(false);
                }
                else
                {
                    TurbineUserPeer.doUpdate((TurbineUser) this, con);
                }
            }

            if (isTurbineUserGroupRolesInitialized())
            {
                for (TurbineUserGroupRole collTurbineUserGroupRoles : getTurbineUserGroupRoles())
                {
                    collTurbineUserGroupRoles.save(con);
                }
            }
        }
        finally
        {
            setSaving(false);
        }
    }




    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key entityId ObjectKey
     */
    public void setPrimaryKey(ObjectKey<?> key)
        
    {
        setEntityId(Integer.valueOf(((NumberKey) key).intValue()));
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key the primary key to set.
     */
    public void setPrimaryKey(String key) 
    {
        setEntityId(new Integer(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey<?> getPrimaryKey()
    {
        return SimpleKey.keyFor(getEntityId());
    }



    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     * @throws TorqueException if retrieval of the associated objects fails  
     */
    public TurbineUser copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using a connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails     
     */
    public TurbineUser copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbineUser copy(boolean deepcopy) throws TorqueException
    {
        TurbineUser turbineUser = new TurbineUser();

        return copyInto(turbineUser, deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbineUser copy(boolean deepcopy, Connection con) throws TorqueException
    {
        TurbineUser turbineUser = new TurbineUser();

        return copyInto(turbineUser, deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbineUser copyInto(TurbineUser copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbineUser copyInto(TurbineUser copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    protected TurbineUser copyInto(TurbineUser copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setEntityId((Integer) null);
        copyObj.setEntityName(entityName);
        copyObj.setPassword(password);
        copyObj.setFirstName(firstName);
        copyObj.setLastName(lastName);
        copyObj.setEmail(email);
        copyObj.setConfirmed(confirmed);
        copyObj.setModifiedDate(modifiedDate);
        copyObj.setCreateDate(createDate);
        copyObj.setLastLogin(lastLogin);
        copyObj.setObjectdata(objectdata);

        if (deepcopy)
        {
            if (collTurbineUserGroupRoles != null)
            {
                for (TurbineUserGroupRole obj : collTurbineUserGroupRoles)
                {
                    copyObj.addTurbineUserGroupRole(obj.copy());
                }
            }
            else
            {
                copyObj.collTurbineUserGroupRoles = null;
            }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbineUser copyInto(TurbineUser copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setEntityId((Integer) null);
        copyObj.setEntityName(entityName);
        copyObj.setPassword(password);
        copyObj.setFirstName(firstName);
        copyObj.setLastName(lastName);
        copyObj.setEmail(email);
        copyObj.setConfirmed(confirmed);
        copyObj.setModifiedDate(modifiedDate);
        copyObj.setCreateDate(createDate);
        copyObj.setLastLogin(lastLogin);
        copyObj.setObjectdata(objectdata);

        if (deepcopy)
        {
            for (TurbineUserGroupRole obj : getTurbineUserGroupRoles(con))
            {
                copyObj.addTurbineUserGroupRole(obj.copy());
            }
        }
        return copyObj;
    }

    /** The Peer class */
    private static final com.uob.om.TurbineUserPeer peer
            = new com.uob.om.TurbineUserPeer();

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public com.uob.om.TurbineUserPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     * @throws TorqueException if associated objects are not found
     */
    public TableMap getTableMap() throws TorqueException
    {
        return com.uob.om.TurbineUserPeer.getTableMap();
    }



    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("TurbineUser:\n");
        str.append("entityId = ")
           .append(getEntityId())
           .append("\n");
        str.append("entityName = ")
           .append(getEntityName())
           .append("\n");
        str.append("password = ")
           .append(getPassword())
           .append("\n");
        str.append("firstName = ")
           .append(getFirstName())
           .append("\n");
        str.append("lastName = ")
           .append(getLastName())
           .append("\n");
        str.append("email = ")
           .append(getEmail())
           .append("\n");
        str.append("confirmed = ")
           .append(getConfirmed())
           .append("\n");
        str.append("modifiedDate = ")
           .append(getModifiedDate())
           .append("\n");
        str.append("createDate = ")
           .append(getCreateDate())
           .append("\n");
        str.append("lastLogin = ")
           .append(getLastLogin())
           .append("\n");
        str.append("objectdata = ")
           .append("<binary>")
           .append("\n");
        return(str.toString());
    }

    /**
     * Compares the primary key of this instance with the key of another.
     *
     * @param toCompare The object to compare to.
     * @return Whether the primary keys are equal and the object have the
     *         same class.
     */
    public boolean equals(Object toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!getClass().equals(toCompare.getClass()))
        {
            return false;
        }
        TurbineUser other = (TurbineUser) toCompare;
        if (getPrimaryKey() == null || other.getPrimaryKey() == null)
        {
            return false;
        }
        return getPrimaryKey().equals(other.getPrimaryKey());
    }

    /**
     * If the primary key is not <code>null</code>, return the hashcode of the
     * primary key.  Otherwise calls <code>Object.hashCode()</code>.
     *
     * @return an <code>int</code> value
     */
    public int hashCode()
    {
        ObjectKey<?> ok = getPrimaryKey();
        if (ok == null)
        {
            return super.hashCode();
        }

        return ok.hashCode();
    }



    /**
     * Compares the content of this object to another object
     *
     * @param toCompare The object to compare to.
     * @return true if all of the columns in the other object have 
     *         the same value as the objects in this class.
     */
    public boolean valueEquals(TurbineUser toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!Objects.equals(this.entityId, toCompare.getEntityId()))
        {
            return false;
        }
        if (!Objects.equals(this.entityName, toCompare.getEntityName()))
        {
            return false;
        }
        if (!Objects.equals(this.password, toCompare.getPassword()))
        {
            return false;
        }
        if (!Objects.equals(this.firstName, toCompare.getFirstName()))
        {
            return false;
        }
        if (!Objects.equals(this.lastName, toCompare.getLastName()))
        {
            return false;
        }
        if (!Objects.equals(this.email, toCompare.getEmail()))
        {
            return false;
        }
        if (!Objects.equals(this.confirmed, toCompare.getConfirmed()))
        {
            return false;
        }
        if (!Objects.equals(this.modifiedDate, toCompare.getModifiedDate()))
        {
            return false;
        }
        if (!Objects.equals(this.createDate, toCompare.getCreateDate()))
        {
            return false;
        }
        if (!Objects.equals(this.lastLogin, toCompare.getLastLogin()))
        {
            return false;
        }
        if (!Objects.equals(this.objectdata, toCompare.getObjectdata()))
        {
            return false;
        }
        return true;
    }



}
