package com.uob.om;

import java.io.Serializable;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.om.ColumnAccessByName;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.util.TorqueConnection;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 *
 * [Sat Jan 24 10:52:43 SGT 2026]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to TurbinePermission
 */
@SuppressWarnings("unused")
public abstract class BaseTurbinePermission extends org.apache.fulcrum.security.torque.turbine.DefaultAbstractTurbinePermission
    implements Persistent, Serializable, ColumnAccessByName
{
    /** Serial version */
    private static final long serialVersionUID = 1769223163043L;



    /** Defines the entityId field. */
    private Integer entityId = null;

    /** Defines the entityName field. */
    private String entityName = null;

    /** Whether this object was modified after loading or after last save. */
    private boolean modified = true;

    /** 
     * Whether this object was loaded from the database or already saved 
     * (false) or whether it is not yet in the database(true).
     */
    private boolean isNew = true;

    /** Flag which indicates whether this object is currently saving. */
    private boolean saving = false;

    /** 
     * Flag which indicates whether this object is currently loaded
     * from the database. 
     */
    private boolean loading = false;

    /** 
     * Flag which indicates whether this object was deleted from the database.
     * Note that this flags does not always display the current database state,
     * there is no magical connection between this flag and the database.
     */
    private boolean deleted = false;



    /** Defines the collTurbineRolePermissions field. */
    protected List<TurbineRolePermission> collTurbineRolePermissions = null;



    /**
     * Get the value of entityId.
     *
     * @return the value of entityId as Integer
     */
    public Integer getEntityId() 
    {
        
        return entityId;
    }

    /**
     * Set the value of entityId.
     *
     * @param v new value of entityId
     */
    public void setEntityId(Integer v)
    {
        if (!Objects.equals(this.entityId, v))
        {
            setModified(true);
        }

        this.entityId = v;

        // update associated objects in collTurbineRolePermissions 
        if (collTurbineRolePermissions != null)
        {
            for (TurbineRolePermission element : collTurbineRolePermissions)
            {
                element.setPermissionId(v);
            }
        }

    }
    
    /**
     * Get the value of entityName.
     *
     * @return the value of entityName as String
     */
    public String getEntityName() 
    {
        
        return entityName;
    }

    /**
     * Set the value of entityName.
     *
     * @param v new value of entityName
     */
    public void setEntityName(String v)
    {
        if (!Objects.equals(this.entityName, v))
        {
            setModified(true);
        }

        this.entityName = v;


    }
    

    /**
     * Returns whether the object has ever been saved.  This will
     * be false, if the object was retrieved from storage or was created
     * and then saved.
     *
     * @return true, if the object has never been persisted.
     */
    public boolean isNew()
    {
        return isNew;
    }

    /**
     * Sets whether the object has ever been saved.
     *
     * @param isNew true if the object has never been saved, false otherwise.
     */
    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }

    /**
     * Returns whether the object has been modified.
     *
     * @return True if the object has been modified.
     */
    public boolean isModified()
    {
        return modified;
    }

    /**
     * Sets whether the object has been modified.
     *
     * @param modified true if the object has been modified, false otherwise.
     */
    public void setModified(boolean modified)
    {
        this.modified = modified;
    }

    /**
     * Sets the modified state for the object to be false.
     */
    public void resetModified()
    {
        modified = false;
    }


    /**
     * Returns whether this object is currently saving.
     *
     * @return true if this object is currently saving, false otherwise.
     */
    public boolean isSaving()
    {
        return saving;
    }

    /**
     * Sets whether this object is currently saving.
     *
     * @param saving true if this object is currently saving, false otherwise.
     */
    public void setSaving(boolean saving)
    {
        this.saving = saving;
    }


    /**
     * Returns whether this object is currently being loaded from the database.
     *
     * @return true if this object is currently loading, false otherwise.
     */
    public boolean isLoading()
    {
        return loading;
    }

    /**
     * Sets whether this object is currently being loaded from the database.
     *
     * @param loading true if this object is currently loading, false otherwise.
     */
    public void setLoading(boolean loading)
    {
        this.loading = loading;
    }


    /**
     * Returns whether this object was deleted from the database.
     * Note that this getter does not automatically reflect database state,
     * it will be set to true by Torque if doDelete() was called with this 
     * object. Bulk deletes and deletes via primary key do not change
     * this flag. Also, if doDelete() was called on an object which does
     * not exist in the database, the deleted flag is set to true even if
     * it was not deleted.
     *
     * @return true if this object was deleted, false otherwise.
     */
    public boolean isDeleted()
    {
        return deleted;
    }

    /**
     * Sets whether this object was deleted from the database.
     *
     * @param deleted true if this object was deleted, false otherwise.
     */
    public void setDeleted(boolean deleted)
    {
        this.deleted = deleted;
    }




    /**
     * Initializes the cache collTurbineRolePermissions for referenced objects.
     * This, means, if collTurbineRolePermissions is null when this operation is called, it is
     * initialized with an empty collection, otherwise it remains unchanged. 
     *
     * @return the (possibly new) content of the field collTurbineRolePermissions, not null.
     */
    public List<TurbineRolePermission> initTurbineRolePermissions()
    {
        if (collTurbineRolePermissions == null)
        {
            collTurbineRolePermissions = new ArrayList<TurbineRolePermission>();
        }
        return collTurbineRolePermissions;
    }

    /**
     * Checks whether the cache collTurbineRolePermissions for referenced objects has either been
     * loaded from the database or has been manually initialized.
     *
     * @return boolean true if initialized
     */
    public boolean isTurbineRolePermissionsInitialized()
    {
        return (collTurbineRolePermissions != null);
    }


    /**
     * Method called to associate a TurbineRolePermission object to this object
     * through the collTurbineRolePermissions foreign key attribute.
     * If the associated objects were not retrieved before
     * and this object is not new, the associated objects are retrieved
     * from the database before adding the <code>toAdd</code> object.
     *
     * @param toAdd the object to add to the associated objects, not null.
     *
     * @throws TorqueException if retrieval of the associated objects fails.
     * @throws NullPointerException if toAdd is null.
     */
    public void addTurbineRolePermission(TurbineRolePermission toAdd)
        throws TorqueException
    {
        toAdd.setTurbinePermission((TurbinePermission) this);
        getTurbineRolePermissions().add(toAdd);
    }

    /**
     * Method called to associate a TurbineRolePermission object to this object
     * through the collTurbineRolePermissions foreign key attribute using connection.
     *
     * @param l TurbineRolePermission
     * @throws TorqueException if retrieval of the associated objects fails.
     */
    public void addTurbineRolePermission(TurbineRolePermission l, Connection con) throws TorqueException
    {
        getTurbineRolePermissions(con).add(l);
        l.setTurbinePermission((TurbinePermission) this);
    }
    
    /**
     * Method called to reset the cache of TurbineRolePermission objects
     * which are related through the collTurbineRolePermissions foreign key attribute.
     */
    public void resetTurbineRolePermission()
    {
        collTurbineRolePermissions = null;
    }


    /**
     * The criteria used to select the current contents of collTurbineRolePermissions
     */
    private transient Criteria lastTurbineRolePermissionCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTurbineRolePermissions(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<TurbineRolePermission> getTurbineRolePermissions()
        throws TorqueException
    {
        if (collTurbineRolePermissions == null)
        {
            collTurbineRolePermissions = getTurbineRolePermissions(new Criteria());
            for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
            {
                turbineRolePermission.setTurbinePermission((TurbinePermission) this);
            }
        }
        return collTurbineRolePermissions;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbinePermission has previously
     * been saved, it will retrieve related collTurbineRolePermissions from storage.
     * If this BaseTurbinePermission is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException If a problem occurs with the get[criteria] method.     
     */
    public List<TurbineRolePermission> getTurbineRolePermissions(Criteria criteria) throws TorqueException
    {
        if (collTurbineRolePermissions == null)
        {
            if (isNew())
            {
               initTurbineRolePermissions();
            }
            else
            {
                criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
                collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelect(criteria);
                for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                {
                    turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                }
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
                if (lastTurbineRolePermissionCriteria == null
                        || !lastTurbineRolePermissionCriteria.equals(criteria))
                {
                    collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelect(criteria);
                    for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                    {
                        turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                    }
                }
            }
        }
        lastTurbineRolePermissionCriteria = criteria;
        return collTurbineRolePermissions;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTurbineRolePermissions(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<TurbineRolePermission> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<TurbineRolePermission> getTurbineRolePermissions(Connection con) throws TorqueException
    {
        if (collTurbineRolePermissions == null)
        {
            collTurbineRolePermissions = getTurbineRolePermissions(new Criteria(), con);
            for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
            {
                turbineRolePermission.setTurbinePermission((TurbinePermission) this);
            }
        }
        return collTurbineRolePermissions;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbinePermission has previously
     * been saved, it will retrieve the related TurbineRolePermission Objects
     * from storage.
     * If this BaseTurbinePermission is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<TurbineRolePermission> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<TurbineRolePermission> getTurbineRolePermissions(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTurbineRolePermissions == null)
        {
            if (isNew())
            {
               initTurbineRolePermissions();
            }
            else
            {
                criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
                collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelect(criteria, con);
                for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                {
                    turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                }
            }
        }
        else
        {
             // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
                if (lastTurbineRolePermissionCriteria == null
                        || !lastTurbineRolePermissionCriteria.equals(criteria))
                {
                    collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelect(criteria, con);
                    for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                    {
                        turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                    }
                }
            }
        }
        lastTurbineRolePermissionCriteria = criteria;

        return collTurbineRolePermissions;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbinePermission is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     *
     * @return List<TurbineRolePermission> the collection
     * @param criteria the criteria to use when filling the collection.
     * @throws TorqueException if associated objects are not found
     */
    protected List<TurbineRolePermission> getTurbineRolePermissionsJoinTurbineRole(Criteria criteria) throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(criteria.getDbName()))
        {
            List<TurbineRolePermission> result = getTurbineRolePermissionsJoinTurbineRole(criteria, connection);

            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseTurbinePermission is new, it will return
     * an empty collection; or if this BaseTurbinePermission has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<TurbineRolePermission> getTurbineRolePermissionsJoinTurbineRole(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collTurbineRolePermissions == null)
        {
            if (isNew())
            {
                initTurbineRolePermissions();
            }
            else
            {
                criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
                collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelectJoinTurbineRole(criteria, connection);
                for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                {
                    turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                }
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(com.uob.om.TurbineRolePermissionPeer.PERMISSION_ID, getEntityId());
            if (lastTurbineRolePermissionCriteria == null
                        || !lastTurbineRolePermissionCriteria.equals(criteria))
            {
                collTurbineRolePermissions = com.uob.om.TurbineRolePermissionPeer.doSelectJoinTurbineRole(criteria, connection);
                for (TurbineRolePermission turbineRolePermission : collTurbineRolePermissions)
                {
                    turbineRolePermission.setTurbinePermission((TurbinePermission) this);
                }
            }
        }
        lastTurbineRolePermissionCriteria = criteria;

        return collTurbineRolePermissions;
    }




    private static final List<String> FIELD_NAMES;

    static
    {
        List<String> fieldNames
                = new ArrayList<String>();
        fieldNames.add("EntityId");
        fieldNames.add("EntityName");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static List<String> getFieldNames()
    {
        return FIELD_NAMES;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("EntityId"))
        {
            return getEntityId();
        }
        if (name.equals("EntityName"))
        {
            return getEntityName();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("EntityId"))
        {
            // Object fields can be null
            if (value != null && ! Integer.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEntityId((Integer) value);
            return true;
        }
        if (name.equals("EntityName"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEntityName((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (com.uob.om.TurbinePermissionPeer.PERMISSION_ID.getSqlExpression().equals(name)
            || com.uob.om.TurbinePermissionPeer.PERMISSION_ID.getColumnName().equals(name))
        {
            return getEntityId();
        }
        if (com.uob.om.TurbinePermissionPeer.PERMISSION_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbinePermissionPeer.PERMISSION_NAME.getColumnName().equals(name))
        {
            return getEntityName();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (com.uob.om.TurbinePermissionPeer.PERMISSION_ID.getSqlExpression().equals(name)
            || com.uob.om.TurbinePermissionPeer.PERMISSION_ID.getColumnName().equals(name))
        {
            return setByName("EntityId", value);
        }
        if (com.uob.om.TurbinePermissionPeer.PERMISSION_NAME.getSqlExpression().equals(name)
            || com.uob.om.TurbinePermissionPeer.PERMISSION_NAME.getColumnName().equals(name))
        {
            return setByName("EntityName", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getEntityId();
        }
        if (pos == 1)
        {
            return getEntityName();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("EntityId", value);
        }
        if (position == 1)
        {
            return setByName("EntityName", value);
        }
        return false;
    }



    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save() throws TorqueException
    {
        save(TurbinePermissionPeer.DATABASE_NAME);
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param dbName the name of the database to which the object
     *        should be saved.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(String dbName) 
            throws TorqueException
    {
        try (TorqueConnection con = Transaction.begin(dbName))
        {
            save(con);
            Transaction.commit(con);
        }
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally.
     *
     * @param con the connection to use for saving the object, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(Connection con) 
            throws TorqueException
    {
        if (isSaving())
        {
            return;
        }
        try
        {
            setSaving(true);
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    TurbinePermissionPeer.doInsert((TurbinePermission) this, con);
                    setNew(false);
                }
                else
                {
                    TurbinePermissionPeer.doUpdate((TurbinePermission) this, con);
                }
            }

            if (isTurbineRolePermissionsInitialized())
            {
                for (TurbineRolePermission collTurbineRolePermissions : getTurbineRolePermissions())
                {
                    collTurbineRolePermissions.save(con);
                }
            }
        }
        finally
        {
            setSaving(false);
        }
    }




    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key entityId ObjectKey
     */
    public void setPrimaryKey(ObjectKey<?> key)
        
    {
        setEntityId(Integer.valueOf(((NumberKey) key).intValue()));
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key the primary key to set.
     */
    public void setPrimaryKey(String key) 
    {
        setEntityId(new Integer(key));
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey<?> getPrimaryKey()
    {
        return SimpleKey.keyFor(getEntityId());
    }



    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     * @throws TorqueException if retrieval of the associated objects fails  
     */
    public TurbinePermission copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using a connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails     
     */
    public TurbinePermission copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbinePermission copy(boolean deepcopy) throws TorqueException
    {
        TurbinePermission turbinePermission = new TurbinePermission();

        return copyInto(turbinePermission, deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbinePermission copy(boolean deepcopy, Connection con) throws TorqueException
    {
        TurbinePermission turbinePermission = new TurbinePermission();

        return copyInto(turbinePermission, deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbinePermission copyInto(TurbinePermission copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbinePermission copyInto(TurbinePermission copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    protected TurbinePermission copyInto(TurbinePermission copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setEntityId((Integer) null);
        copyObj.setEntityName(entityName);

        if (deepcopy)
        {
            if (collTurbineRolePermissions != null)
            {
                for (TurbineRolePermission obj : collTurbineRolePermissions)
                {
                    copyObj.addTurbineRolePermission(obj.copy());
                }
            }
            else
            {
                copyObj.collTurbineRolePermissions = null;
            }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public TurbinePermission copyInto(TurbinePermission copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setEntityId((Integer) null);
        copyObj.setEntityName(entityName);

        if (deepcopy)
        {
            for (TurbineRolePermission obj : getTurbineRolePermissions(con))
            {
                copyObj.addTurbineRolePermission(obj.copy());
            }
        }
        return copyObj;
    }

    /** The Peer class */
    private static final com.uob.om.TurbinePermissionPeer peer
            = new com.uob.om.TurbinePermissionPeer();

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public com.uob.om.TurbinePermissionPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     * @throws TorqueException if associated objects are not found
     */
    public TableMap getTableMap() throws TorqueException
    {
        return com.uob.om.TurbinePermissionPeer.getTableMap();
    }



    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("TurbinePermission:\n");
        str.append("entityId = ")
           .append(getEntityId())
           .append("\n");
        str.append("entityName = ")
           .append(getEntityName())
           .append("\n");
        return(str.toString());
    }

    /**
     * Compares the primary key of this instance with the key of another.
     *
     * @param toCompare The object to compare to.
     * @return Whether the primary keys are equal and the object have the
     *         same class.
     */
    public boolean equals(Object toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!getClass().equals(toCompare.getClass()))
        {
            return false;
        }
        TurbinePermission other = (TurbinePermission) toCompare;
        if (getPrimaryKey() == null || other.getPrimaryKey() == null)
        {
            return false;
        }
        return getPrimaryKey().equals(other.getPrimaryKey());
    }

    /**
     * If the primary key is not <code>null</code>, return the hashcode of the
     * primary key.  Otherwise calls <code>Object.hashCode()</code>.
     *
     * @return an <code>int</code> value
     */
    public int hashCode()
    {
        ObjectKey<?> ok = getPrimaryKey();
        if (ok == null)
        {
            return super.hashCode();
        }

        return ok.hashCode();
    }



    /**
     * Compares the content of this object to another object
     *
     * @param toCompare The object to compare to.
     * @return true if all of the columns in the other object have 
     *         the same value as the objects in this class.
     */
    public boolean valueEquals(TurbinePermission toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!Objects.equals(this.entityId, toCompare.getEntityId()))
        {
            return false;
        }
        if (!Objects.equals(this.entityName, toCompare.getEntityName()))
        {
            return false;
        }
        return true;
    }



}
