package com.uob.om;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

import org.apache.torque.NoRowsException;
import org.apache.torque.TooManyRowsException;
import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.criteria.Criterion;
import org.apache.torque.om.mapper.RecordMapper;
import org.apache.torque.om.mapper.CompositeMapper;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.map.TableMap;
import org.apache.torque.util.TorqueConnection;
import org.apache.torque.util.Transaction;
import org.apache.torque.util.ColumnValues;
import org.apache.torque.util.JdbcTypedValue;



/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Jan 24 10:52:47 SGT 2026]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to GtpUserGroupRolePeer
 */

@SuppressWarnings("unused")
public abstract class BaseGtpUserGroupRolePeerImpl
    extends org.apache.torque.util.AbstractPeerImpl<GtpUserGroupRole>
{
    /** Serial version */
    private static final long serialVersionUID = 1769223167766L;



    /**
     * Constructor.
     * The recordMapper, tableMap and databaseName fields are correctly
     * initialized.
     */
    public BaseGtpUserGroupRolePeerImpl()
    {
        this(new GtpUserGroupRoleRecordMapper(),
            GtpUserGroupRolePeer.TABLE,
            GtpUserGroupRolePeer.DATABASE_NAME);
    }

    /**
     * Constructor providing the objects to be injected as parameters.
     *
     * @param recordMapper a record mapper to map JDBC result sets to objects
     * @param tableMap the default table map
     * @param databaseName the name of the database
     */
    public BaseGtpUserGroupRolePeerImpl(
            RecordMapper<GtpUserGroupRole> recordMapper, 
            TableMap tableMap,
            String databaseName)
    {
        super(recordMapper, tableMap, databaseName);
    }


    /**
     * Returns a new instance of the Data object class
     */
    public GtpUserGroupRole getDbObjectInstance()
    {
        return new GtpUserGroupRole();
    }


    /**
     * Method to do updates.  This method is to be used during a transaction,
     * otherwise use the doUpdate(Criteria) method.
     *
     * @param columnValues the values to update plus the primary key
     *        identifying the row to update.
     * @param con the connection to use, not null.
     *
     * @return the number of affected rows.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public int doUpdate(ColumnValues columnValues, Connection con)
        throws TorqueException
    {
        Criteria selectCriteria = new Criteria(getDatabaseName());
        correctBooleans(columnValues);

        {
            JdbcTypedValue pkValue
                = columnValues.remove(GtpUserGroupRolePeer.USER_ID);
            if (pkValue == null)
            {
                throw new TorqueException(
                        "The value for the primary key column "
                        + "GtpUserGroupRolePeer.USER_ID"
                        + " must be set");
            }
            if (pkValue.getSqlExpression() == null)
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.USER_ID,
                        pkValue.getValue());
            }
            else
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.USER_ID,
                        pkValue.getSqlExpression());
            }
        }
        {
            JdbcTypedValue pkValue
                = columnValues.remove(GtpUserGroupRolePeer.GROUP_ID);
            if (pkValue == null)
            {
                throw new TorqueException(
                        "The value for the primary key column "
                        + "GtpUserGroupRolePeer.GROUP_ID"
                        + " must be set");
            }
            if (pkValue.getSqlExpression() == null)
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.GROUP_ID,
                        pkValue.getValue());
            }
            else
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.GROUP_ID,
                        pkValue.getSqlExpression());
            }
        }
        {
            JdbcTypedValue pkValue
                = columnValues.remove(GtpUserGroupRolePeer.ROLE_ID);
            if (pkValue == null)
            {
                throw new TorqueException(
                        "The value for the primary key column "
                        + "GtpUserGroupRolePeer.ROLE_ID"
                        + " must be set");
            }
            if (pkValue.getSqlExpression() == null)
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.ROLE_ID,
                        pkValue.getValue());
            }
            else
            {
                selectCriteria.where(
                        GtpUserGroupRolePeer.ROLE_ID,
                        pkValue.getSqlExpression());
            }
        }


        int rowCount = doUpdate(selectCriteria, columnValues, con);
        return rowCount;
    }

    /**
     * Deletes a data object, i.e. a row in a table, in the database.
     *
     * @param obj the data object to delete in the database, not null.
     *
     * @return the number of deleted rows.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public int doDelete(GtpUserGroupRole obj) throws TorqueException
    {
        int result = doDelete(buildCriteria(obj.getPrimaryKey()));
        obj.setDeleted(true);
        return result;
    }

    /**
     * Deletes a data object, i.e. a row in a table, in the database.
     * This method is to be used during a transaction, otherwise use the
     * doDelete(GtpUserGroupRole) method.
     *
     * @param obj the data object to delete in the database, not null.
     * @param con the connection to use, not null.
     *
     * @return the number of deleted rows.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public int doDelete(GtpUserGroupRole obj, Connection con)
        throws TorqueException
    {
        int result = doDelete(buildCriteria(obj.getPrimaryKey()), con);
        obj.setDeleted(true);
        return result;
    }

    /**
     * Deletes data objects, i.e. rows in a table, in the database.
     *
     * @param objects the data object to delete in the database, not null,
     *        may not contain null.
     *
     * @return the number of deleted rows.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public int doDelete(Collection<GtpUserGroupRole> objects)
            throws TorqueException
    {
        int result = doDelete(buildPkCriteria(objects));
        objects.forEach(object -> object.setDeleted(true));
        return result;
    }

    /**
     * Deletes data objects, i.e. rows in a table, in the database.
     * This method uses the passed connection to delete the rows;
     * if a transaction is open in the connection, the deletion happens inside
     * this transaction.
     *
     * @param objects the data objects to delete in the database, not null,
     *        may not contain null.
     * @param con the connection to use for deleting, not null.
     *
     * @return the number of deleted rows.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public int doDelete(
            Collection<GtpUserGroupRole> objects,
            Connection con)
        throws TorqueException
    {
        int result = doDelete(buildPkCriteria(objects), con);
        objects.forEach(object -> object.setDeleted(true));
        return result;
    }

    /** 
     * Build a Criteria object which selects all objects which have a given
     * primary key.
     *
     * @param pk the primary key value to build the criteria from, not null.
     */
    public Criteria buildCriteria(ObjectKey<?> pk)
    {
        Criteria criteria = new Criteria();
        SimpleKey<?>[] keys = (SimpleKey[])pk.getValue();
        criteria.and(GtpUserGroupRolePeer.USER_ID, keys[0]);
        criteria.and(GtpUserGroupRolePeer.GROUP_ID, keys[1]);
        criteria.and(GtpUserGroupRolePeer.ROLE_ID, keys[2]);
        return criteria;
     }

    /** 
     * Build a Criteria object which selects all objects which primary keys
     * are contained in the passed collection.
     *
     * @param pks the primary key values to build the criteria from, not null,
     *        may not contain null.
     */
    public Criteria buildCriteria(Collection<ObjectKey<?>> pks)
    {
        Criteria criteria = new Criteria();
        for (ObjectKey<?> pk : pks)
        {
            SimpleKey<?>[] keys = (SimpleKey[])pk.getValue();
                Criterion c0 = new Criterion(
                    GtpUserGroupRolePeer.USER_ID, keys[0], Criteria.EQUAL);
                Criterion c1 = new Criterion(
                    GtpUserGroupRolePeer.GROUP_ID, keys[1], Criteria.EQUAL);
                    c0.and(c1);
                Criterion c2 = new Criterion(
                    GtpUserGroupRolePeer.ROLE_ID, keys[2], Criteria.EQUAL);
                    c1.and(c2);
            criteria.or(c0);
        }
        return criteria;
     }


    /** 
     * Build a Criteria object which selects all passed objects using their
     * primary key. Objects which do not yet have a primary key are ignored.
     *
     * @param objects the objects to build the criteria from, not null,
     *        may not contain null.
     */
    public Criteria buildPkCriteria(
            Collection<GtpUserGroupRole> objects)
    {
        return buildCriteria(objects.stream()
                .map(object -> object.getPrimaryKey())
                .collect(Collectors.toList()));
    }

    /** 
     * Build a Criteria object from the data object for this peer.
     *
     * @param obj the object to build the criteria from, not null.
     */
    public Criteria buildCriteria(GtpUserGroupRole obj)
    {
        Criteria criteria = new Criteria(getDatabaseName());
        criteria.and(GtpUserGroupRolePeer.USER_ID, obj.getUserId());
        criteria.and(GtpUserGroupRolePeer.GROUP_ID, obj.getGroupId());
        criteria.and(GtpUserGroupRolePeer.ROLE_ID, obj.getRoleId());
        return criteria;
    }

    /** 
     * Build a Criteria object from the data object for this peer,
     * skipping all binary columns.
     *
     * @param obj the object to build the criteria from, not null.
     */
    public Criteria buildSelectCriteria(GtpUserGroupRole obj)
    {
        Criteria criteria = new Criteria(getDatabaseName());
        criteria.and(GtpUserGroupRolePeer.USER_ID, obj.getUserId());
        criteria.and(GtpUserGroupRolePeer.GROUP_ID, obj.getGroupId());
        criteria.and(GtpUserGroupRolePeer.ROLE_ID, obj.getRoleId());
        return criteria;
    }

    /** 
     * Returns the contents of the object as ColumnValues object.
     * Primary key columns which are generated on insertion are not
     * added to the returned object if they still have their initial
     * value. Also, columns which have the useDatabaseDefaultValue
     * flag set to true are also not added to the returned object
     * if they still have their initial value.
     *
     * @throws TorqueException if the table map cannot be retrieved
     *         (should not happen).
     */
    public ColumnValues buildColumnValues(GtpUserGroupRole gtpUserGroupRole)
            throws TorqueException
    {
        ColumnValues columnValues = new ColumnValues();
        columnValues.put(
                GtpUserGroupRolePeer.USER_ID,
                new JdbcTypedValue(
                    gtpUserGroupRole.getUserId(),
                    4));
        columnValues.put(
                GtpUserGroupRolePeer.GROUP_ID,
                new JdbcTypedValue(
                    gtpUserGroupRole.getGroupId(),
                    4));
        columnValues.put(
                GtpUserGroupRolePeer.ROLE_ID,
                new JdbcTypedValue(
                    gtpUserGroupRole.getRoleId(),
                    4));
        return columnValues;
    }

    /**
     * retrieve object using using pk values.
     *
     * @param userId int
     * @param groupId int
     * @param roleId int
     */
    public GtpUserGroupRole retrieveByPK(
            int userId,
            int groupId,
            int roleId)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            GtpUserGroupRole result = retrieveByPK(
               userId,
               groupId,
               roleId,
               connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * retrieve object using using pk values.
     *
     * @param userId int
     * @param groupId int
     * @param roleId int
     * @param con Connection
     */
    public GtpUserGroupRole retrieveByPK(
            int userId,
            int groupId,
            int roleId,
            Connection con) throws TorqueException
    {

        Criteria criteria = new Criteria();
        criteria.and(GtpUserGroupRolePeer.USER_ID, userId);
        criteria.and(GtpUserGroupRolePeer.GROUP_ID, groupId);
        criteria.and(GtpUserGroupRolePeer.ROLE_ID, roleId);
        GtpUserGroupRole v = doSelectSingleRecord(criteria, con);
        if (v == null)
        {
            throw new NoRowsException("Failed to select a row.");
        }

        return v;
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public GtpUserGroupRole retrieveByPK(ObjectKey<?> pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            GtpUserGroupRole result = retrieveByPK(pk, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public GtpUserGroupRole retrieveByPK(ObjectKey<?> pk, Connection con)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Criteria criteria = buildCriteria(pk);
        GtpUserGroupRole v = doSelectSingleRecord(criteria, con);
        if (v == null)
        {
            throw new NoRowsException("Failed to select a row.");
        }

        return v;
    }


    /**
     * Retrieve multiple objects by pk.
     *
     * @param pks List of primary keys.
     *        Entries in pks which do not match entries in the database are ignored.
     *
     * @return the list of matching objects, not null.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> retrieveByObjectKeys(Collection<ObjectKey<?>> pks)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result = retrieveByObjectKeys(pks, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * Retrieve multiple objects by pk.
     *
     * @param pks List of primary keys.
     *        Entries in pks which do not match entries in the database are ignored.
     * @param dbcon the connection to use
     *
     * @return the list of matching objects, not null.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> retrieveByObjectKeys(
                Collection<ObjectKey<?>> pks,
                Connection dbcon)
            throws TorqueException
    {
        if (pks == null || pks.size() == 0)
        {
            return new ArrayList<GtpUserGroupRole>();
        }
        Criteria criteria = buildCriteria(pks);
        List<GtpUserGroupRole> result = doSelect(criteria, dbcon);
        return result;
    }


    /**
     * Selects a collection of dbObjectClassName objects pre-filled with their
     * GtpUser objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpUser(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinGtpUser(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * Selects a collection of GtpUserGroupRole objects pre-filled with their
     * GtpUser objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpUser(
            Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        addSelectColumns(criteria);
        com.uob.om.GtpUserPeer.addSelectColumns(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(
                new GtpUserGroupRoleRecordMapper(),
                0);
        compositeMapper.addMapper(
                new GtpUserRecordMapper(),
                GtpUserGroupRolePeer.numColumns);
        criteria.addJoin(GtpUserGroupRolePeer.USER_ID,
            com.uob.om.GtpUserPeer.USER_ID);

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole obj1 = (GtpUserGroupRole) rawResultRow.get(0);
            GtpUser obj2 = (GtpUser) rawResultRow.get(1);

            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                GtpUserGroupRole temp_obj1 = result.get(j);
                com.uob.om.GtpUser temp_obj2 = temp_obj1.getGtpUser();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(obj1);
            }
            result.add(obj1);
        }
        return result;
    }
    /**
     * Selects a collection of dbObjectClassName objects pre-filled with their
     * GtpGroup objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpGroup(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinGtpGroup(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * Selects a collection of GtpUserGroupRole objects pre-filled with their
     * GtpGroup objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpGroup(
            Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        addSelectColumns(criteria);
        com.uob.om.GtpGroupPeer.addSelectColumns(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(
                new GtpUserGroupRoleRecordMapper(),
                0);
        compositeMapper.addMapper(
                new GtpGroupRecordMapper(),
                GtpUserGroupRolePeer.numColumns);
        criteria.addJoin(GtpUserGroupRolePeer.GROUP_ID,
            com.uob.om.GtpGroupPeer.GROUP_ID);

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole obj1 = (GtpUserGroupRole) rawResultRow.get(0);
            GtpGroup obj2 = (GtpGroup) rawResultRow.get(1);

            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                GtpUserGroupRole temp_obj1 = result.get(j);
                com.uob.om.GtpGroup temp_obj2 = temp_obj1.getGtpGroup();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(obj1);
            }
            result.add(obj1);
        }
        return result;
    }
    /**
     * Selects a collection of dbObjectClassName objects pre-filled with their
     * GtpRole objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpRole(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinGtpRole(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * Selects a collection of GtpUserGroupRole objects pre-filled with their
     * GtpRole objects.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public List<GtpUserGroupRole> doSelectJoinGtpRole(
            Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        addSelectColumns(criteria);
        com.uob.om.GtpRolePeer.addSelectColumns(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(
                new GtpUserGroupRoleRecordMapper(),
                0);
        compositeMapper.addMapper(
                new GtpRoleRecordMapper(),
                GtpUserGroupRolePeer.numColumns);
        criteria.addJoin(GtpUserGroupRolePeer.ROLE_ID,
            com.uob.om.GtpRolePeer.ROLE_ID);

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole obj1 = (GtpUserGroupRole) rawResultRow.get(0);
            GtpRole obj2 = (GtpRole) rawResultRow.get(1);

            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                GtpUserGroupRole temp_obj1 = result.get(j);
                com.uob.om.GtpRole temp_obj2 = temp_obj1.getGtpRole();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(obj1);
            }
            result.add(obj1);
        }
        return result;
    }

    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpUser(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinAllExceptGtpUser(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpUser(Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(new GtpUserGroupRoleRecordMapper(), 0);
        GtpUserGroupRolePeer.addSelectColumns(criteria);
        int offset = GtpUserGroupRolePeer.numColumns;
 
        com.uob.om.GtpGroupPeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.GROUP_ID, com.uob.om.GtpGroupPeer.GROUP_ID);
        compositeMapper.addMapper(new GtpGroupRecordMapper(), offset);
        offset = offset + com.uob.om.GtpGroupPeer.numColumns;
 
        com.uob.om.GtpRolePeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.ROLE_ID, com.uob.om.GtpRolePeer.ROLE_ID);
        compositeMapper.addMapper(new GtpRoleRecordMapper(), offset);
        offset = offset + com.uob.om.GtpRolePeer.numColumns;

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole gtpUserGroupRole = (GtpUserGroupRole) rawResultRow.get(0);

            com.uob.om.GtpGroup obj1 = (com.uob.om.GtpGroup) rawResultRow.get(1);
            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpGroup temp_obj1 = temp_gtpUserGroupRole.getGtpGroup();
                if (temp_obj1.getPrimaryKey().equals(obj1.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj1.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj1.initGtpUserGroupRoles();
                obj1.addGtpUserGroupRole(gtpUserGroupRole);
            }

            com.uob.om.GtpRole obj2 = (com.uob.om.GtpRole) rawResultRow.get(2);
            newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpRole temp_obj2 = temp_gtpUserGroupRole.getGtpRole();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(gtpUserGroupRole);
            }
            result.add(gtpUserGroupRole);
        }
        return result;
    }
    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpGroup(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinAllExceptGtpGroup(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpGroup(Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(new GtpUserGroupRoleRecordMapper(), 0);
        GtpUserGroupRolePeer.addSelectColumns(criteria);
        int offset = GtpUserGroupRolePeer.numColumns;
 
        com.uob.om.GtpUserPeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.USER_ID, com.uob.om.GtpUserPeer.USER_ID);
        compositeMapper.addMapper(new GtpUserRecordMapper(), offset);
        offset = offset + com.uob.om.GtpUserPeer.numColumns;
 
        com.uob.om.GtpRolePeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.ROLE_ID, com.uob.om.GtpRolePeer.ROLE_ID);
        compositeMapper.addMapper(new GtpRoleRecordMapper(), offset);
        offset = offset + com.uob.om.GtpRolePeer.numColumns;

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole gtpUserGroupRole = (GtpUserGroupRole) rawResultRow.get(0);

            com.uob.om.GtpUser obj1 = (com.uob.om.GtpUser) rawResultRow.get(1);
            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpUser temp_obj1 = temp_gtpUserGroupRole.getGtpUser();
                if (temp_obj1.getPrimaryKey().equals(obj1.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj1.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj1.initGtpUserGroupRoles();
                obj1.addGtpUserGroupRole(gtpUserGroupRole);
            }

            com.uob.om.GtpRole obj2 = (com.uob.om.GtpRole) rawResultRow.get(2);
            newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpRole temp_obj2 = temp_gtpUserGroupRole.getGtpRole();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(gtpUserGroupRole);
            }
            result.add(gtpUserGroupRole);
        }
        return result;
    }
    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpRole(Criteria criteria)
        throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(getDatabaseName()))
        {
            List<GtpUserGroupRole> result
                    = GtpUserGroupRolePeer.doSelectJoinAllExceptGtpRole(criteria, connection);
            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * selects a collection of GtpUserGroupRole objects pre-filled with
     * related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GtpUserGroupRolePeerImpl.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected List<GtpUserGroupRole> doSelectJoinAllExceptGtpRole(Criteria criteria, Connection conn)
        throws TorqueException
    {
        setDbName(criteria);

        CompositeMapper compositeMapper = new CompositeMapper();
        compositeMapper.addMapper(new GtpUserGroupRoleRecordMapper(), 0);
        GtpUserGroupRolePeer.addSelectColumns(criteria);
        int offset = GtpUserGroupRolePeer.numColumns;
 
        com.uob.om.GtpUserPeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.USER_ID, com.uob.om.GtpUserPeer.USER_ID);
        compositeMapper.addMapper(new GtpUserRecordMapper(), offset);
        offset = offset + com.uob.om.GtpUserPeer.numColumns;
 
        com.uob.om.GtpGroupPeer.addSelectColumns(criteria);
        criteria.addJoin(GtpUserGroupRolePeer.GROUP_ID, com.uob.om.GtpGroupPeer.GROUP_ID);
        compositeMapper.addMapper(new GtpGroupRecordMapper(), offset);
        offset = offset + com.uob.om.GtpGroupPeer.numColumns;

        correctBooleans(criteria);

        List<GtpUserGroupRole> result = new ArrayList<GtpUserGroupRole>();
        List<List<Object>> rawResult = doSelect(
                criteria, compositeMapper, conn);
        for (List<Object> rawResultRow : rawResult)
        {
            GtpUserGroupRole gtpUserGroupRole = (GtpUserGroupRole) rawResultRow.get(0);

            com.uob.om.GtpUser obj1 = (com.uob.om.GtpUser) rawResultRow.get(1);
            boolean newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpUser temp_obj1 = temp_gtpUserGroupRole.getGtpUser();
                if (temp_obj1.getPrimaryKey().equals(obj1.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj1.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj1.initGtpUserGroupRoles();
                obj1.addGtpUserGroupRole(gtpUserGroupRole);
            }

            com.uob.om.GtpGroup obj2 = (com.uob.om.GtpGroup) rawResultRow.get(2);
            newObject = true;
            for (int j = 0; j < result.size(); j++)
            {
                com.uob.om.GtpUserGroupRole temp_gtpUserGroupRole = result.get(j);
                com.uob.om.GtpGroup temp_obj2 = temp_gtpUserGroupRole.getGtpGroup();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addGtpUserGroupRole(gtpUserGroupRole);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initGtpUserGroupRoles();
                obj2.addGtpUserGroupRole(gtpUserGroupRole);
            }
            result.add(gtpUserGroupRole);
        }
        return result;
    }



}
