package com.uob.om;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.torque.Column;
import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.om.mapper.RecordMapper;
import org.apache.torque.om.mapper.MappingStrategy;


/**
 * Maps ResultSet rows into GtpUserGroupRole objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Jan 24 10:52:48 SGT 2026]
 *
 */
@SuppressWarnings("unused")
public class BaseGtpUserGroupRoleRecordMapper implements RecordMapper<GtpUserGroupRole>
{
    /** Serial version */
    private static final long serialVersionUID = 1769223168822L;

    /** The class log. */
    private static Log log
            = LogFactory.getLog(BaseGtpUserGroupRoleRecordMapper.class);
            
    private static final String USER_ID_EXPRESSION = BaseGtpUserGroupRolePeer.USER_ID.getSqlExpression();
    private static final String GROUP_ID_EXPRESSION = BaseGtpUserGroupRolePeer.GROUP_ID.getSqlExpression();
    private static final String ROLE_ID_EXPRESSION = BaseGtpUserGroupRolePeer.ROLE_ID.getSqlExpression();

    private boolean useMappingStrategy = true;

    private MappingStrategy<GtpUserGroupRole> strategy;
    
    public void initStrategy()
    {
        this.strategy = new MappingStrategy<GtpUserGroupRole>();
    }
    

    /**
     * Constructs the object from the current row in the resultSet.
     *
     * @param resultSet the resultSet to operate on, already pointing
     *        to the correct row. Not null.
     * @param offset a possible offset in the columns to be considered
     *        (if previous columns contain other objects),
     *        or 0 for no offset.
     * @param criteria The criteria which created the result set.
     *        If set, the attributes to set in the data object
     *        are determined from the select columns in the criteria;
     *        if no matching column can be found, null is returned.
     *        If not set, all of the table's columns are read from the
     *        result set in the order defined in the table definition.
     *
     * @return the mapped object, not null.
     *
     * @throws TorqueException when reading fields from the RecordSet fails
     *         or if a Criteria is passed which contains select columns other
     *         than the columns in the GTP_USER_GROUP_ROLE table.
     */
    public GtpUserGroupRole processRow(
                ResultSet resultSet,
                int offset,
                Criteria criteria)
            throws TorqueException
    {
        GtpUserGroupRole gtpUserGroupRole = new GtpUserGroupRole();

        try 
        {
            gtpUserGroupRole.setLoading(true);
            if (criteria == null)
            {
                gtpUserGroupRole.setUserId(
                        getUserId(resultSet, offset + 1));
                gtpUserGroupRole.setGroupId(
                        getGroupId(resultSet, offset + 2));
                gtpUserGroupRole.setRoleId(
                        getRoleId(resultSet, offset + 3));
            }
            else
            {
                if (useMappingStrategy) {
                    initStrategy();
                }
                // try to get columns to be mapped
                // from criteria's select columns
                int totalOffset = offset + 1;
                List<Column> selectColumns = criteria.getSelectColumns();
                List<Column> columnsWithoutOffset = selectColumns.subList(
                        offset, 
                        selectColumns.size());
                Set<String> columnsMapped = new HashSet<String>();
                for (Column column : columnsWithoutOffset)
                {
                    final int nextOffset = totalOffset;                     if (!columnsMapped.contains(USER_ID_EXPRESSION ) && USER_ID_EXPRESSION.equals(
                            column.getSqlExpression()))
                    {
                        if (useMappingStrategy) 
                        {
                            strategy.addColumn(nextOffset, 
                                (res, inst) -> inst.setUserId( getUserId(res, nextOffset)));
                        } else
                        {
                            gtpUserGroupRole.setUserId( getUserId(resultSet, totalOffset));
                        }
                        columnsMapped.add( USER_ID_EXPRESSION );
                    }
                    else if (!columnsMapped.contains(GROUP_ID_EXPRESSION ) && GROUP_ID_EXPRESSION.equals(
                            column.getSqlExpression()))
                    {
                        if (useMappingStrategy) 
                        {
                            strategy.addColumn(nextOffset, 
                                (res, inst) -> inst.setGroupId( getGroupId(res, nextOffset)));
                        } else
                        {
                            gtpUserGroupRole.setGroupId( getGroupId(resultSet, totalOffset));
                        }
                        columnsMapped.add( GROUP_ID_EXPRESSION );
                    }
                    else if (!columnsMapped.contains(ROLE_ID_EXPRESSION ) && ROLE_ID_EXPRESSION.equals(
                            column.getSqlExpression()))
                    {
                        if (useMappingStrategy) 
                        {
                            strategy.addColumn(nextOffset, 
                                (res, inst) -> inst.setRoleId( getRoleId(res, nextOffset)));
                        } else
                        {
                            gtpUserGroupRole.setRoleId( getRoleId(resultSet, totalOffset));
                        }
                        columnsMapped.add( ROLE_ID_EXPRESSION );
                    }
                    totalOffset++;
                }
                if (columnsMapped.isEmpty())
                {
                    log.debug("no columns to map found in criteria, "
                        + "returning null");
                    return null;
                }
                if (useMappingStrategy)
                {
                  this.strategy.finish(3, true);
                  this.strategy.execute(resultSet, gtpUserGroupRole);
                }
            }
            gtpUserGroupRole.setNew(false);
            gtpUserGroupRole.setModified(false);
        }
        finally
        {
            gtpUserGroupRole.setLoading(false);
        }
        return gtpUserGroupRole;
    }

    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field userId in GtpUserGroupRole.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected int getUserId(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getInt(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field groupId in GtpUserGroupRole.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected int getGroupId(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getInt(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field roleId in GtpUserGroupRole.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected int getRoleId(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getInt(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }

}
