package com.mycompany.webapp.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 17:41:28 SGT 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class TurbineGroup
    extends com.mycompany.webapp.om.BaseTurbineGroup
    implements org.apache.fulcrum.security.model.turbine.entity.TurbineGroup
{
    /** Serial version */
    private static final long serialVersionUID = 1756114888583L;



}
