package com.mycompany.webapp.om;


/**
 * Maps ResultSet rows into TurbineRolePermission objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 25 17:41:30 SGT 2025]
 *
 */
public class TurbineRolePermissionRecordMapper extends BaseTurbineRolePermissionRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1756114890173L;



}
